// ============================================================
// KANDIDAT PART1 (PLAN-026) — kata mudah tambahan untuk tier 1.
// Dipilih dari pool kata BEBAS (tidak ada di tier 2-10) sehingga
// dedup global tidak memangkas tier lain. Clue TIDAK memuat
// jawaban (word-boundary). Engine fix-plan026.mjs memfilter
// (bukan di tier1/tiar lain, bukan duplikat) lalu menulis
// src/data/vocabulary/tier1-part1.ts.
// ============================================================
export const PART1 = [
  // ---- hewan (bukan yang dipakai SWAP tier 2-10) ----
  ["walrus", "hewan laut besar bertaring panjang", "singa laut dari daerah dingin", "Gadingnya panjang menonjol"],
  ["kasuari", "burung besar tak bisa terbang dari Papua", "burung berjambul di kepala", "Kepalanya berwarna biru"],
  ["tapir", "hewan berbelalai pendek berkulit tebal", "hewan mirip babi bermoncong panjang", "Moncongnya seperti belalai kecil"],
  ["bajing", "hewan pengerat yang pandai melompat di pohon", "hewan kecil berekor lebat", "Sinonim: tupai"],
  ["biawak", "kadal besar yang hidup di darat dan air", "reptil besar berlidah bercabang", "Sinonim: kadal besar"],
  ["komodo", "kadal raksasa khas Indonesia", "hewan purba dari Pulau Komodo", "Sinonim: biawak komodo"],
  ["tokek", "cicak besar yang bersuara tokek", "kadal malam yang sering di dinding", "Suaranya terdengar di malam hari"],
  ["cecak", "reptil kecil perekat di dinding", "hewan kecil pemakan nyamuk", "Sinonim: cicak"],
  ["bunglon", "kadal yang bisa mengubah warna kulit", "hewan yang menyamar dengan warna", "Sinonim: kadal pohon"],
  ["iguana", "kadal besar berduri di punggung", "kadal herbivora dari daerah tropis", "Sinonim: kadal iguana"],
  ["kobra", "ular berbisa dengan leher mengembang", "ular yang bisa mendesis keras", "Sinonim: ular sendok"],
  ["belut", "ikan panjang licin yang hidup di lumpur", "ikan mirip ular di sawah", "Sinonim: ikan belut"],
  ["gurame", "ikan air tawar yang lezat digoreng", "ikan budidaya yang suka melompat", "Sinonim: ikan gurame"],
  ["patin", "ikan air tawar berbadan panjang", "ikan yang sering dibuat sup asam", "Sinonim: ikan patin"],
  ["gabus", "ikan air tawar yang kuat di lumpur", "ikan predator di rawa", "Sinonim: ikan gabus"],
  ["tenggiri", "ikan laut yang enak dijadikan sambal", "ikan berbadan panjang dari laut", "Sinonim: ikan tenggiri"],
  ["kakap", "ikan laut yang dagingnya tebal", "ikan favorit untuk digoreng", "Sinonim: ikan kakap"],
  ["bawal", "ikan laut berbadan pipih", "ikan yang sering digoreng utuh", "Sinonim: ikan bawal"],
  ["teri", "ikan kecil yang diasinkan", "ikan kecil untuk topping nasi", "Sinonim: ikan teri"],
  ["hiu", "ikan laut pemangsa bergigi tajam", "ikan besar yang ditakuti perenang", "Siripnya dibuat sup"],
  ["pari", "ikan bertubuh pipih berekor panjang", "ikan yang bisa melayang di air", "Sinonim: ikan pari"],
  ["pesut", "mamalia air tawar yang ramah", "lumba-lumba sungai di Kalimantan", "Sinonim: lumba-lumba air tawar"],
  ["kakatua", "burung berjambul yang bisa meniru suara", "burung peliharaan yang cerdas", "Jambulnya berwarna-warni"],
  ["parkit", "burung kecil berwarna cerah", "burung peliharaan yang riang", "Sering dipelihara dalam sangkar"],
  ["jalak", "burung hitam yang pandai meniru suara", "burung yang sering dilatih bicara", "Sinonim: burung beo"],
  ["murai", "burung berkicau berekor panjang", "burung lomba kicau yang populer", "Ekornya panjang dan indah"],
  ["kutilang", "burung kecil berjambul hitam", "burung yang riang berkicau", "Sinonim: burung kutilang"],
  ["perkutut", "burung merpati kecil bersuara merdu", "burung yang sering dipelihara orang Jawa", "Sinonim: burung perkutut"],
  ["tekukur", "burung mirip merpati bersuara khas", "burung yang suaranya seperti mengetuk", "Sinonim: burung derkuku"],
  ["kijang", "rusa kecil yang larinya cepat", "hewan herbivora bertanduk kecil", "Sinonim: rusa kecil"],
  ["luwak", "musang pemakan biji kopi", "hewan kecil penghasil kopi terkenal", "Sinonim: musang"],
  ["siamang", "kera hitam bersuara nyaring", "primata lengan panjang", "Sinonim: kera siamang"],
  ["entok", "bebek besar berwarna gelap", "unggas air yang jinak", "Sinonim: itik manila"],
  ["itik", "unggas air penghasil telur", "bebek kecil peliharaan", "Sinonim: bebek"],
  ["pelikan", "burung besar berparuh berkantong", "burung pemakan ikan berparuh panjang", "Sinonim: burung undan"],
  ["kuntul", "burung putih berkaki panjang", "bangau putih yang berdiri di sawah", "Sinonim: bangau putih"],
  ["nuri", "burung berwarna cerah dari timur", "burung beo kecil berwarna merah", "Sinonim: burung kakatua kecil"],
  ["keong", "hewan bercangkang yang merayap pelan", "siput yang hidup di air", "Sinonim: siput"],
  ["bekicot", "siput besar yang bisa dimakan", "keong darat berukuran besar", "Sinonim: siput besar"],
  ["rajungan", "kepiting laut dengan capit", "kepiting yang hidup di pasir pantai", "Sinonim: kepiting laut"],
  ["wereng", "serangga kecil pengisap padi", "hama padi yang merusak tanaman", "Sinonim: hama wereng"],
  ["berudu", "anak katak yang hidup di air", "kecebong berekor", "Sinonim: kecebong"],
  ["merak", "burung besar berbulu indah", "burung dengan ekor yang bisa mengembang", "Ekor jantannya seperti kipas"],
  ["pipit", "burung kecil yang suka memakan padi", "burung pengganggu di sawah", "Sinonim: burung pipit"],
  ["walet", "burung kecil penghasil sarang mahal", "burung yang sarangnya dari air liur", "Sinonim: burung walet"],
  ["mencit", "tikus kecil yang sering dipakai percobaan", "tikus putih berukuran kecil", "Sinonim: tikus kecil"],
  ["hamster", "hewan pengerat kecil yang dipelihara", "hewan mungil suka mengumpulkan makanan", "Sinonim: marmut kecil"],
  ["sagu", "tepung dari batang pohon palem", "bahan makanan pokok di wilayah timur", "Diolah menjadi papeda"],
  ["lovebird", "burung kecil yang setia pada pasangannya", "burung cinta yang jinak", "Sinonim: burung cinta"],
  ["kijang", "rusa kecil yang larinya cepat", "hewan herbivora bertanduk kecil", "Sinonim: rusa kecil"],
  // ---- makanan ----
  ["ketupat", "nasi yang dibungkus anyaman daun", "makanan khas hari raya", "Sinonim: nasi ketupat"],
  ["lontong", "nasi yang dipadatkan dalam daun", "nasi gulung yang dipotong bulat", "Sinonim: ketupat panjang"],
  ["opor", "masakan berkuah santan berwarna kuning", "lauk ayam berkuah santan", "Sinonim: opor ayam"],
  ["rendang", "masakan daging berkuah santan kering", "makanan khas Padang yang pedas", "Sinonim: rendang daging"],
  ["gulai", "masakan berkuah santan khas Padang", "sayur atau daging berkuah santan", "Sinonim: gulai nangka"],
  ["rawon", "sup daging khas Jawa berwarna hitam", "makanan berkuah hitam dari kluwek", "Sinonim: sop daging hitam"],
  ["pempek", "makanan khas Palembang dari ikan", "adonan ikan yang disajikan dengan cuko", "Sinonim: pempek palembang"],
  ["pepes", "makanan yang dibungkus daun pisang", "ikan yang dibakar dalam daun", "Sinonim: pepes ikan"],
  ["botok", "makanan kukus dari kelapa parut", "lauk berdaun yang dibungkus pisang", "Sinonim: botok tempe"],
  ["urap", "sayur rebus dengan kelapa parut", "salad sayur khas Jawa", "Sinonim: sayur urap"],
  ["rujak", "buah dicampur sambal pedas", "makanan buah dengan bumbu kacang", "Sinonim: rujak buah"],
  ["asinan", "sayur atau buah yang diasinkan", "makanan segar berkuah asam pedas", "Sinonim: asinan sayur"],
  ["acar", "sayur yang direndam cuka", "lauk pendamping yang segar", "Sinonim: acar timun"],
  ["terasi", "bumbu udang yang dihaluskan", "pasta udang untuk sambal", "Sinonim: belacan"],
  ["klepon", "kue bulat hijau berisi gula merah", "jajanan kenyal dari tepung ketan", "Sinonim: kue onde kecil"],
  ["getuk", "kue dari singkong yang direbus", "jajanan manis dari ketela", "Sinonim: getuk lindri"],
  ["lemper", "nasi ketan berisi ayam", "jajanan khas Jawa berbungkus daun", "Sinonim: lemper ayam"],
  ["dodol", "manisan kenyal dari buah dan gula", "kue lengket khas Garut", "Sinonim: dodol garut"],
  ["wajik", "kue manis dari ketan dan gula", "jajanan lengket khas Jawa", "Sinonim: wajik ketan"],
  ["apem", "kue kukus dari tepung beras", "jajanan tradisional yang lembut", "Sinonim: kue apem"],
  ["serabi", "kue dari tepung beras dan santan", "pancake khas Bandung", "Sinonim: kue serabi"],
  ["martabak", "kue tebal berisi telur atau cokelat", "jajanan manis atau asin yang digoreng", "Sinonim: martabak manis"],
  ["risoles", "makanan goreng berisi ragout", "kroket berbalut tepung panir", "Sinonim: risol"],
  ["pastel", "kue goreng berisi sayur dan bihun", "pai goreng kecil", "Sinonim: pastel goreng"],
  ["lumpia", "makanan goreng berisi rebung", "kulit tipis berisi sayur", "Sinonim: lumpia semarang"],
  ["siomay", "makanan kukus dari ikan dan tepung", "bakso ikan yang dikukus", "Sinonim: dimsum ikan"],
  ["batagor", "bakso tahu goreng khas Bandung", "tahu goreng dengan saus kacang", "Sinonim: bakso tahu goreng"],
  ["cilok", "jajanan kenyal dari tepung kanji", "bakso aci yang direbus", "Sinonim: cilok bandung"],
  ["cireng", "jajanan goreng dari tepung kanji", "aci yang digoreng renyah", "Sinonim: aci goreng"],
  ["perkedel", "gorengan dari kentang tumbuk", "lauk bulat pipih dari kentang", "Sinonim: perkedel kentang"],
  ["kroket", "gorengan berisi ragout dibalut panir", "makanan goreng dari kentang", "Sinonim: kroket kentang"],
  ["bakwan", "gorengan berisi sayur", "adonan tepung goreng dengan sayuran", "Sinonim: ote-ote"],
  ["bolu", "kue lembut dari tepung dan telur", "kue yang dipanggang mengembang", "Sinonim: kue bolu"],
  ["pukis", "kue manis yang dipanggang kecil", "jajanan berbentuk setengah lingkaran", "Sinonim: kue pukis"],
  ["cengkeh", "rempah kering yang harum", "bumbu yang dipakai untuk rokok", "Sinonim: bunga cengkeh"],
  ["pala", "rempah beraroma khas", "biji rempah untuk bumbu masak", "Sinonim: biji pala"],
  ["jinten", "rempah kecil yang harum", "biji bumbu untuk masakan", "Sinonim: jintan"],
  ["lada", "rempah pedas yang dihaluskan", "bumbu hitam atau putih", "Sinonim: merica"],
  ["mayones", "saus kental dari telur dan minyak", "saus putih untuk salad", "Sinonim: saus mayo"],
  ["tapioka", "tepung dari singkong", "tepung kanji yang kenyal", "Sinonim: tepung kanji"],
  ["ragi", "bahan pengembang adonan", "mikroorganisme untuk membuat tape", "Sinonim: ragi tape"],
  ["tape", "makanan manis dari singkong atau ketan", "singkong yang difermentasi", "Sinonim: tapai"],
  ["wijen", "biji kecil yang ditaburkan di makanan", "biji putih yang harum saat disangrai", "Sinonim: biji wijen"],
  ["almond", "kacang pipih yang gurih", "kacang untuk susu dan kue", "Sinonim: kacang almond"],
  ["santan", "perasan kelapa yang berwarna putih", "cairan dari parutan kelapa", "Bahan kuah gulai dan opor"],
  ["kismis", "anggur kering yang manis", "buah anggur yang dikeringkan", "Sering ada di roti dan kue"],
  ["biskuit", "kue kering yang renyah", "camilan kering dari tepung", "Sinonim: kue kering"],
  ["keripik", "irisan tipis yang digoreng kering", "camilan renyah dari kentang", "Sinonim: kripik"],
  ["gurih", "rasa sedap seperti kaldu", "rasa yang tidak manis dan tidak asin", "Antonim: hambar"],
  // ---- tubuh ----
  ["geraham", "gigi besar untuk mengunyah", "gigi belakang yang lebar", "Sinonim: gigi geraham"],
  ["dagu", "bagian wajah di bawah mulut", "bagian bawah dari wajah", "Sinonim: rahang bawah"],
  ["pelipis", "bagian kepala di samping mata", "sisi kepala yang berdenyut saat pusing", "Sinonim: bagian pelipis"],
  ["kening", "bagian wajah di atas mata", "dahi yang berkerut saat marah", "Sinonim: dahi"],
  ["urat", "pembuluh yang terlihat di kulit", "benang dalam tubuh yang mengalirkan darah", "Sinonim: pembuluh darah"],
  ["nadi", "tempat denyut di pergelangan tangan", "titik yang terasa berdenyut", "Sinonim: denyut nadi"],
  ["betis", "bagian kaki belakang di bawah lutut", "otot di belakang tulang kering", "Sinonim: otot betis"],
  ["paha", "bagian kaki di atas lutut", "bagian kaki yang paling tebal", "Sinonim: pangkal paha"],
  ["ketiak", "bagian dalam lipatan lengan", "tempat yang mudah berkeringat", "Sinonim: lipatan lengan"],
  ["pusar", "bekas tali pusar di perut", "lubang kecil di tengah perut", "Sinonim: udel"],
  ["limpa", "organ penyaring darah di perut", "organ tubuh di sisi kiri perut", "Sinonim: limpa"],
  ["gusi", "daging yang membungkus akar gigi", "bagian merah di dalam mulut", "Sinonim: gusi gigi"],
  ["pupil", "bagian hitam di tengah mata", "lubang mata yang mengatur cahaya", "Sinonim: biji mata"],
  ["retina", "lapisan peka cahaya di mata", "bagian mata yang menangkap gambar", "Sinonim: selaput mata"],
  ["kornea", "selaput bening di depan mata", "bagian depan mata yang transparan", "Sinonim: selaput bening mata"],
  ["cuping", "bagian bawah daun telinga", "daging lembut di ujung telinga", "Sinonim: cuping telinga"],
  ["jakun", "tonjolan di leher laki-laki", "bagian leher yang menonjol saat menelan", "Sinonim: jakun"],
  ["alis", "rambut halus di atas mata", "lengkung rambut pelindung mata", "Sinonim: alis mata"],
  // ---- rumah & dapur ----
  ["guling", "bantal panjang untuk berpelukan", "bantal panjang untuk tidur", "Sinonim: bantal guling"],
  ["sprei", "kain penutup kasur", "alas tidur yang dicuci", "Sinonim: seprei"],
  ["tikar", "alas duduk dari anyaman", "anyaman bambu untuk alas", "Sinonim: alas anyaman"],
  ["taplak", "kain penutup meja", "kain alas di atas meja", "Sinonim: taplak meja"],
  ["baskom", "wadah besar untuk mencuci", "mangkuk besar dari plastik", "Sinonim: ember lebar"],
  ["timba", "wadah untuk menimba air", "ember bertali untuk sumur", "Sinonim: ember timba"],
  ["kuali", "wajan cekung untuk memasak", "panci besar dari tanah atau besi", "Sinonim: kuali besar"],
  ["dandang", "panci untuk mengukus nasi", "alat memasak nasi dengan uap", "Sinonim: panci kukus"],
  ["kukusan", "alat untuk mengukus makanan", "anyaman bambu tempat mengukus", "Sinonim: alat kukus"],
  ["irus", "sendok besar untuk mengambil kuah", "centong sayur berlubang", "Sinonim: sendok sayur"],
  ["centong", "sendok besar untuk nasi", "alat untuk mengambil nasi", "Sinonim: sendok nasi"],
  ["sutil", "alat untuk membalik gorengan", "spatula dapur", "Sinonim: spatula"],
  ["talenan", "alas untuk memotong di dapur", "papan pemotong sayur", "Sinonim: papan potong"],
  ["cobek", "wadah batu untuk mengulek", "mangkuk batu untuk sambal", "Sinonim: lumpang batu"],
  ["ulekan", "alat batu untuk menghaluskan bumbu", "penumbuk di atas cobek", "Sinonim: penumbuk bumbu"],
  ["lesung", "wadah batu atau kayu untuk menumbuk", "lumpang besar untuk padi", "Sinonim: lumpang"],
  ["alu", "penumbuk panjang untuk lesung", "kayu pemukul untuk menumbuk", "Sinonim: penumbuk padi"],
  ["tampah", "anyaman bundar untuk menjemur", "niru besar dari bambu", "Sinonim: niru besar"],
  ["nyiru", "anyaman bundar untuk menampi beras", "tampah yang lebih kecil", "Sinonim: tampah kecil"],
  ["bakul", "keranjang beras dari anyaman", "wadah nasi dari anyaman bambu", "Sinonim: keranjang nasi"],
  ["gentong", "wadah besar untuk air", "tempayan besar dari tanah", "Sinonim: tempayan besar"],
  ["tempayan", "wadah besar dari tanah liat", "gentong untuk menyimpan air", "Sinonim: gentong air"],
  ["kendi", "wadah air dari tanah liat", "teko tradisional tanpa cerat", "Sinonim: kendi air"],
  ["teko", "wadah untuk menuang teh", "ceret untuk air panas", "Sinonim: teko teh"],
  ["cerek", "wadah untuk merebus air", "teko logam di atas kompor", "Sinonim: ceret"],
  ["termos", "wadah yang menjaga air tetap panas", "botol penyimpan air panas", "Sinonim: botol termos"],
  ["kloset", "tempat buang air di toilet", "jamban duduk", "Sinonim: toilet duduk"],
  ["jamban", "tempat buang air kecil atau besar", "kakus sederhana", "Sinonim: kakus"],
  ["kran", "alat untuk membuka aliran air", "keran air di wastafel", "Sinonim: keran"],
  ["corong", "alat untuk menuang cairan ke botol", "kerucut berlubang untuk mengisi", "Sinonim: corong minyak"],
  ["ayakan", "alat untuk memisahkan tepung", "saringan berlubang halus", "Sinonim: saringan tepung"],
  ["parutan", "alat untuk memarut kelapa", "alat penghalus keju", "Sinonim: alat parut"],
  ["loyang", "cetakan untuk memanggang kue", "wadah datar untuk kue", "Sinonim: cetakan kue"],
  ["ember", "wadah untuk menampung air", "benda yang diisi air untuk mandi", "Sinonim: timba"],
  ["sapu", "alat untuk membersihkan lantai", "alat berikat lidi untuk menyapu", "Sinonim: penyapu"],
  ["bantal", "alas kepala saat tidur", "benda empuk yang dipeluk saat tidur", "Sinonim: guling"],
  ["selimut", "kain tebal penutup tubuh saat tidur", "kain hangat untuk menutup badan", "Sinonim: kemul"],
  ["lampu", "alat penerang yang menyala", "benda yang menerangi ruangan gelap", "Sinonim: pelita"],
  ["lilin", "benda yang menyala dengan sumbu", "penerang yang bisa meleleh", "Sinonim: dian"],
  // ---- kantor & alat ----
  ["binder", "penjepit dokumen dari logam", "alat menjepit kertas", "Sinonim: penjepit kertas"],
  ["stapler", "alat untuk menjepit kertas dengan isi", "alat tembak pengikat kertas", "Sinonim: penjepit isi"],
  ["rautan", "alat untuk menajamkan pensil", "pengasah pensil", "Sinonim: peraut pensil"],
  ["perekat", "bahan untuk merekatkan benda", "lem yang menempelkan kertas", "Sinonim: lem"],
  ["selotip", "pita perekat transparan", "lakban tipis untuk kertas", "Sinonim: pita perekat"],
  ["lakban", "pita perekat yang kuat", "isolasi yang lengket kuat", "Sinonim: plester perekat"],
  ["mistar", "alat ukur panjang yang lurus", "penggaris panjang", "Sinonim: penggaris"],
  ["spons", "benda lembut penyerap air", "alat pencuci yang berpori", "Sinonim: busa pencuci"],
  ["pensil", "alat tulis yang bisa dihapus", "alat menulis berbahan grafit", "Sinonim: potlot"],
  ["penghapus", "alat untuk menghapus tulisan pensil", "benda karet untuk menghapus", "Sinonim: hapus"],
  ["penggaris", "alat untuk mengukur panjang", "alat untuk membuat garis lurus", "Sinonim: mistar"],
  // ---- alam ----
  ["rawa", "tanah basah yang digenangi air", "daerah berlumpur penuh tanaman air", "Sinonim: paya-paya"],
  ["muara", "tempat sungai bertemu laut", "ujung hilir sebuah sungai", "Sinonim: mulut sungai"],
  ["hulu", "bagian awal sebuah sungai", "sumber air di pegunungan", "Sinonim: mata air sungai"],
  ["hilir", "bagian akhir sebuah sungai", "arah menuju laut", "Sinonim: bagian bawah sungai"],
  ["arus", "aliran air atau listrik", "gerakan air yang mengalir", "Sinonim: aliran"],
  ["lahar", "aliran lumpur dari gunung berapi", "lumpur panas gunung meletus", "Sinonim: lahar dingin"],
  ["magma", "batuan cair di dalam bumi", "lava yang masih di perut bumi", "Sinonim: batuan cair"],
  ["waduk", "danau buatan untuk menampung air", "bendungan besar penyimpan air", "Sinonim: bendungan air"],
  ["bendung", "tanggul untuk menahan air sungai", "pembangkit aliran irigasi", "Sinonim: dam"],
  ["irigasi", "pengairan sawah secara teratur", "saluran air untuk pertanian", "Sinonim: pengairan sawah"],
  ["jeram", "aliran sungai yang deras berbatu", "air terjun kecil yang cepat", "Sinonim: jeram sungai"],
  ["curug", "air terjun dalam bahasa Sunda", "air terjun di daerah Jawa Barat", "Sinonim: air terjun"],
  ["gerimis", "hujan sangat halus", "rintik hujan yang kecil lembut", "Sinonim: hujan gerimis"],
  ["rintik", "titik-titik hujan yang kecil", "butiran air hujan awal", "Sinonim: rintik hujan"],
  ["kemarau", "musim kering tanpa hujan", "musim panas yang panjang", "Sinonim: musim kering"],
  ["batu", "benda keras yang bukan logam", "material padat dari alam", "Sinonim: bebatuan"],
  ["bara", "batu hitam yang bisa terbakar", "arang yang menyala tanpa api", "Sinonim: bara api"],
  ["embun", "titik air yang menempel di daun pagi hari", "air yang muncul di pagi hari", "Sinonim: titik air"],
  ["kabut", "uap air pekat yang mengaburkan pandangan", "awan rendah di permukaan tanah", "Sinonim: halimun"],
  ["pelangi", "busur warna-warni di langit setelah hujan", "warna indah berbentuk setengah lingkaran", "Sinonim: bianglala"],
  ["pasir", "butiran halus di pantai atau sungai", "material yang dibuat kaca", "Sinonim: pasel"],
  ["lumpur", "tanah yang basah dan lembek", "tanah yang becek setelah hujan", "Sinonim: lempung"],
  ["debu", "partikel halus yang beterbangan", "kotoran halus yang menempel di meja", "Sinonim: abu"],
  ["asap", "gas kelabu yang keluar dari api", "uap dari pembakaran", "Sinonim: jelaga"],
  ["ranting", "cabang kecil pada pohon", "batang kecil yang bisa patah", "Sinonim: dahan"],
  ["duri", "bagian tajam pada batang tanaman", "sesuatu yang menusuk di batang mawar", "Sinonim: onak"],
  ["biji", "bagian dalam buah yang bisa ditanam", "bakal tanaman baru", "Sinonim: benih"],
  // ---- warna & batu ----
  ["krem", "warna seperti kulit telur", "warna krem yang lembut", "Sinonim: warna krem"],
  ["tosca", "warna biru kehijauan", "warna seperti air laut dangkal", "Sinonim: warna turquoise"],
  ["maroon", "warna merah tua kecokelatan", "warna merah bata gelap", "Sinonim: warna merah tua"],
  ["navy", "warna biru sangat tua", "warna biru seperti seragam angkatan laut", "Sinonim: biru tua"],
  ["lembayung", "warna ungu kemerahan", "warna seperti langit senja", "Sinonim: warna ungu tua"],
  ["magenta", "warna merah keunguan", "warna cerah antara merah dan ungu", "Sinonim: warna fuchsia"],
  ["amber", "warna kuning kecokelatan", "warna seperti madu tua", "Sinonim: warna kuning tua"],
  ["ivory", "warna putih gading", "warna putih kekuningan", "Sinonim: warna gading"],
  ["burgundy", "warna merah anggur gelap", "warna merah keunguan tua", "Sinonim: warna merah anggur"],
  ["indigo", "warna biru keunguan", "warna di antara biru dan ungu", "Sinonim: warna nila"],
  ["olive", "warna hijau kecokelatan", "warna seperti buah zaitun", "Sinonim: hijau zaitun"],
  ["zamrud", "batu mulia berwarna hijau", "warna hijau tua yang indah", "Sinonim: batu zamrud"],
  ["pirus", "batu mulia berwarna biru kehijauan", "warna seperti laut tropis", "Sinonim: warna pirus"],
  ["lilac", "warna ungu muda", "warna ungu pucat yang lembut", "Sinonim: warna ungu muda"],
  ["plum", "warna ungu kemerahan", "warna seperti buah prem", "Sinonim: warna prem"],
  ["intan", "batu mulia paling keras", "berlian yang belum diasah", "Sinonim: berlian"],
  ["ruby", "batu mulia berwarna merah", "permata merah yang mahal", "Sinonim: batu merah delima"],
  ["safir", "batu mulia berwarna biru", "permata biru yang indah", "Sinonim: batu biru"],
  ["topas", "batu mulia berwarna kuning", "permata kuning yang bening", "Sinonim: batu topas"],
  ["akik", "batu cincin berwarna indah", "batu permata untuk cincin", "Sinonim: batu akik"],
  ["giok", "batu permata berwarna hijau", "batu hijau yang dijadikan perhiasan", "Sinonim: batu giok"],
  ["marmar", "batu alam berurat indah", "marmer untuk lantai", "Sinonim: marmer"],
  ["basalt", "batu hitam dari lava", "batu beku yang keras", "Sinonim: batu lava"],
  ["andesit", "batu gunung yang keras", "batu abu-abu dari gunung berapi", "Sinonim: batu andesit"],
  ["gamping", "batu kapur berwarna putih", "bahan untuk membuat kapur", "Sinonim: batu kapur"],
  ["nikel", "logam perak yang kuat", "logam untuk membuat baterai", "Sinonim: logam nikel"],
  ["seng", "logam tipis untuk atap", "lembaran logam pelapis atap", "Sinonim: atap seng"],
  ["krom", "logam berkilau untuk hiasan", "lapisan logam mengilap", "Sinonim: logam krom"],
  // ---- sains & angka ----
  ["fusi", "penggabungan dua hal menjadi satu", "energi matahari dari penggabungan inti", "Sinonim: penggabungan"],
  ["fisi", "pembelahan inti atom", "energi nuklir dari pembelahan", "Sinonim: pembelahan inti"],
  ["volt", "satuan ukur tegangan listrik", "ukuran kekuatan aliran listrik", "Sinonim: tegangan listrik"],
  ["ampere", "satuan ukur kuat arus listrik", "ukuran banyaknya listrik mengalir", "Sinonim: kuat arus"],
  ["watt", "satuan ukur daya listrik", "ukuran kekuatan lampu", "Sinonim: daya listrik"],
  ["ohm", "satuan hambatan listrik", "ukuran penghambat arus", "Sinonim: hambatan listrik"],
  ["hertz", "satuan frekuensi getaran", "ukuran jumlah getaran per detik", "Sinonim: satuan frekuensi"],
  ["desibel", "satuan ukur kekuatan suara", "ukuran kerasnya bunyi", "Sinonim: ukuran suara"],
  ["gema", "bunyi yang memantul kembali", "suara yang bergema di gua", "Sinonim: gaung"],
  ["gaung", "suara yang terdengar berulang", "gema di tempat luas", "Sinonim: pantulan bunyi"],
  ["dengung", "bunyi rendah yang terus-menerus", "suara seperti lebah terbang", "Sinonim: bunyi berdengung"],
  ["vokal", "huruf hidup a i u e o", "bunyi bahasa tanpa hambatan", "Sinonim: huruf vokal"],
  ["konsonan", "huruf mati selain vokal", "bunyi bahasa dengan hambatan", "Sinonim: huruf konsonan"],
  ["fonem", "satuan bunyi terkecil bahasa", "bunyi yang membedakan arti kata", "Sinonim: bunyi bahasa"],
  ["morfem", "satuan kata terkecil yang bermakna", "bagian terkecil dari kata", "Sinonim: unit bahasa"],
  ["diksi", "pilihan kata yang tepat", "pemilihan kata dalam menulis", "Sinonim: pilihan kata"],
  ["bilangan", "kata untuk menyatakan jumlah", "angka dalam hitungan", "Sinonim: angka"],
  ["genap", "bilangan yang habis dibagi dua", "angka berpasangan", "Antonim: ganjil"],
  ["prima", "bilangan yang hanya bisa dibagi satu dan dirinya", "angka seperti dua, tiga, lima", "Sinonim: bilangan prima"],
  ["desimal", "bilangan dengan tanda koma", "angka dalam sistem sepuluh", "Sinonim: bilangan pecahan"],
  ["rasio", "perbandingan antara dua angka", "angka yang menunjukkan perbandingan", "Sinonim: perbandingan"],
  ["digit", "satu angka dalam sebuah bilangan", "huruf angka seperti nol sampai sembilan", "Sinonim: angka"],
  ["kerucut", "bangun ruang yang lancip di atas", "bangun seperti topi ulang tahun", "Sinonim: bangun kerucut"],
  ["limas", "bangun ruang dengan alas segi banyak", "bangun seperti piramida", "Sinonim: piramida"],
  ["prisma", "bangun ruang dengan dua alas sama", "bangun tiga dimensi berpotongan lurus", "Sinonim: bangun prisma"],
  ["trapesium", "bangun datar dengan dua sisi sejajar", "segi empat yang miring ke atas", "Sinonim: bangun trapesium"],
  ["poligon", "bangun datar bersisi banyak", "segi banyak seperti segi lima", "Sinonim: segi banyak"],
  ["kurva", "garis lengkung yang tidak lurus", "garis bengkok pada grafik", "Sinonim: garis lengkung"],
  ["lancip", "ujung yang runcing", "sudut yang kurang dari siku-siku", "Antonim: tumpul"],
  ["tumpul", "ujung yang tidak tajam", "sudut yang lebih dari siku-siku", "Antonim: lancip"],
  ["siku", "bagian lengan yang membengkok", "sudut yang membentuk huruf L", "Sinonim: siku-siku"],
  ["elips", "bentuk bulat lonjong", "lingkaran yang dipanjangkan", "Sinonim: lonjong"],
  ["oval", "bentuk seperti telur", "bulat panjang seperti telur", "Sinonim: lonjong"],
  ["deret", "barisan angka yang berurutan", "susunan berurutan", "Sinonim: barisan"],
  ["matriks", "susunan angka dalam baris dan kolom", "tabel angka untuk hitungan", "Sinonim: tabel angka"],
  ["aljabar", "ilmu hitung dengan huruf pengganti angka", "matematika dengan simbol x dan y", "Sinonim: ilmu aljabar"],
  ["inci", "satuan panjang sebesar ruas jari", "ukuran panjang sekitar dua setengah sentimeter", "Sinonim: satuan inci"],
  ["yard", "satuan panjang hampir satu meter", "ukuran panjang tiga kaki", "Sinonim: satuan yard"],
  ["kuintal", "satuan berat seratus kilogram", "ukuran berat hasil panen", "Sinonim: seratus kilogram"],
  ["mililiter", "satuan kecil untuk cairan", "seperseribu liter", "Sinonim: satuan mililiter"],
  ["kubik", "satuan ukur isi atau volume", "pangkat tiga dari sebuah ukuran", "Sinonim: meter kubik"],
  ["hektar", "satuan luas lahan yang besar", "ukuran tanah seluas sepuluh ribu meter", "Sinonim: sepuluh ribu meter persegi"],
  // ---- sifat & perasaan ----
  ["gesit", "bergerak cepat dan lincah", "tangkas dalam bergerak", "Sinonim: lincah"],
  ["lawas", "sudah lama sekali", "berusia tua dalam waktu", "Sinonim: lama"],
  ["ikhtiar", "usaha untuk mencapai sesuatu", "upaya dengan sungguh-sungguh", "Sinonim: usaha"],
  ["rehat", "berhenti sejenak untuk istirahat", "beristirahat sebentar", "Sinonim: istirahat"],
  ["bersila", "duduk dengan kaki bersilang", "duduk seperti orang bersemedi", "Sinonim: duduk bersila"],
  ["merangkak", "bergerak dengan tangan dan lutut", "cara bayi bergerak sebelum berjalan", "Sinonim: jalan merangkak"],
  ["cangkung", "berjongkok dengan lutut ditekuk", "posisi tubuh merendah", "Sinonim: berjongkok"],
  ["berjinjit", "berdiri dengan ujung kaki", "berdiri di atas jari kaki", "Sinonim: jinjit"],
  ["tekun", "rajin dan sungguh-sungguh", "giat dalam mengerjakan sesuatu", "Sinonim: rajin"],
  ["ulet", "tidak mudah menyerah", "gigih dalam berusaha", "Sinonim: gigih"],
  ["tabah", "kuat menghadapi cobaan", "tidak mudah menangis saat sedih", "Sinonim: sabar"],
  ["irit", "hemat dalam pemakaian", "tidak boros menggunakan sesuatu", "Sinonim: hemat"],
  ["boros", "pemakaian yang berlebihan", "tidak hemat", "Antonim: hemat"],
  ["kalem", "tenang dan tidak terburu-buru", "santai dalam bersikap", "Sinonim: tenang"],
  ["lugas", "langsung pada pokok persoalan", "tidak berbelit-belit dalam bicara", "Sinonim: tegas"],
  ["sembrono", "kurang hati-hati dalam bertindak", "ceroboh dalam bekerja", "Sinonim: ceroboh"],
  ["teledor", "lalai dalam tugas", "kurang perhatian pada kewajiban", "Sinonim: lalai"],
  ["lalai", "tidak ingat akan kewajiban", "lupa karena tidak fokus", "Sinonim: teledor"],
  ["rinci", "terurai sampai bagian terkecil", "terperinci dengan jelas", "Sinonim: terperinci"],
  ["parsial", "hanya sebagian saja", "tidak menyeluruh", "Sinonim: sebagian"],
  ["jenuh", "bosan karena terlalu lama", "rasa bosan yang menumpuk", "Sinonim: bosan"],
  ["muak", "merasa bosan hingga mual", "tidak tahan lagi melihat sesuatu", "Sinonim: jijik"],
  ["gemas", "merasa kesal karena lucu", "ingin mencubit karena menggemaskan", "Sinonim: kesal"],
  ["sebal", "merasa jengkel dalam hati", "kesal karena kecewa", "Sinonim: jengkel"],
  ["dongkol", "marah yang terpendam", "kesal karena diperlakukan tidak adil", "Sinonim: kesal"],
  ["geram", "marah yang meledak-ledak", "sangat marah", "Sinonim: marah"],
  ["angan", "khayalan atau harapan", "bayangan dalam pikiran", "Sinonim: khayalan"],
  ["lamunan", "pikiran yang melayang jauh", "angan-angan yang berkelana", "Sinonim: angan-angan"],
  ["idaman", "sesuatu yang sangat diinginkan", "cita-cita yang didambakan", "Sinonim: dambaan"],
  ["congkak", "merasa paling hebat", "sombong dalam bersikap", "Sinonim: sombong"],
  ["niat", "maksud dalam hati", "keinginan untuk berbuat", "Sinonim: maksud"],
  ["azam", "tekad yang kuat", "niat yang bulat", "Sinonim: tekad"],
  ["ikrar", "janji yang diucapkan sungguh-sungguh", "pernyataan kesetiaan", "Sinonim: janji"],
  ["bakti", "tanda hormat dan setia", "perbuatan baik kepada orang tua", "Sinonim: hormat"],
  ["abdi", "orang yang mengabdi", "pelayan yang setia", "Sinonim: pelayan"],
  ["petuah", "nasihat yang bijak", "kata-kata penuntun hidup", "Sinonim: nasihat"],
  ["wejangan", "pesan yang berisi nasihat", "petuah dari orang tua", "Sinonim: nasihat"],
  ["tausiah", "ceramah agama yang menasihati", "kajian yang memberi petunjuk", "Sinonim: ceramah"],
  ["mufakat", "kesepakatan bersama", "kata sepakat dalam musyawarah", "Sinonim: sepakat"],
  ["syair", "puisi lama bersajak a-a-a-a", "karya sastra berbait", "Sinonim: puisi"],
  ["pantun", "puisi lama bersajak a-b-a-b", "karya sastra empat baris", "Sinonim: puisi lama"],
  ["gurindam", "puisi lama berisi nasihat", "sajak dua baris yang berpetuah", "Sinonim: puisi nasihat"],
  ["kidung", "nyanyian atau syair pujian", "lagu yang dilantunkan merdu", "Sinonim: nyanyian"],
  ["tembang", "nyanyian Jawa yang syahdu", "lagu tradisional bersyair", "Sinonim: lagu"],
  ["koor", "nyanyian bersama oleh banyak orang", "paduan suara", "Sinonim: paduan suara"],
  ["solois", "penyanyi yang tampil sendiri", "pemain musik tunggal", "Sinonim: penyanyi tunggal"],
  ["duet", "tampil berdua dalam bernyanyi", "lagu yang dinyanyikan dua orang", "Sinonim: berdua"],
  ["trio", "kelompok yang berjumlah tiga", "tampil bertiga", "Sinonim: bertiga"],
  ["lakon", "cerita dalam pertunjukan", "peran yang dimainkan aktor", "Sinonim: drama"],
  ["akrobat", "gerakan badan yang sulit", "pertunjukan melompat dan berputar", "Sinonim: atraksi sirkus"],
  ["duka", "rasa sedih yang dalam", "kesedihan karena kehilangan", "Antonim: suka"],
  ["pusara", "tempat makam diletakkan", "kuburan yang ditandai batu", "Sinonim: kuburan"],
  ["kremasi", "pembakaran jenazah", "proses membakar mayat", "Sinonim: pembakaran jenazah"],
  ["keranda", "peti untuk membawa jenazah", "usungan jenazah", "Sinonim: peti jenazah"],
  ["flu", "penyakit pilek yang menular", "sakit karena virus", "Sinonim: influenza"],
  ["pilek", "hidung berair karena masuk angin", "sakit ringan di hidung", "Sinonim: masuk angin"],
  ["maag", "sakit pada lambung", "nyeri perut karena asam lambung", "Sinonim: sakit lambung"],
  ["kram", "otot menegang dan sakit", "kejang pada otot", "Sinonim: kejang otot"],
  ["pegal", "rasa sakit pada otot", "badan terasa kaku", "Sinonim: linu"],
  ["linu", "rasa sakit pada tulang", "nyeri seperti ditusuk", "Sinonim: pegal"],
  ["asma", "penyakit sesak napas", "sakit napas yang kambuh-kambuhan", "Sinonim: sesak napas"],
  ["tifus", "penyakit demam akibat bakteri", "sakit demam tinggi yang lama", "Sinonim: tipes"],
  ["kolera", "penyakit mencret yang menular", "sakit perut akibat bakteri air", "Sinonim: penyakit mencret"],
  ["campak", "penyakit kulit berbintik merah", "sakit demam dengan ruam", "Sinonim: penyakit campak"],
  ["rabun", "penglihatan kurang jelas", "tidak bisa melihat jauh dengan tajam", "Sinonim: rabun jauh"],
  ["katarak", "selaput yang mengaburkan mata", "penyakit mata yang membuat buram", "Sinonim: penyakit mata"],
  ["tuli", "tidak bisa mendengar", "hilangnya kemampuan mendengar", "Sinonim: pekak"],
  ["bisu", "tidak bisa berbicara", "hilangnya kemampuan bicara", "Sinonim: tidak bisa bicara"],
  ["suntik", "memasukkan obat dengan jarum", "cara memberi vaksin", "Sinonim: injeksi"],
  ["infus", "cairan obat yang masuk ke pembuluh", "cairan yang dialirkan ke tubuh", "Sinonim: cairan infus"],
  ["koyo", "plester obat untuk nyeri", "tambal penghangat di kulit", "Sinonim: plester obat"],
  ["kasa", "kain halus untuk membalut luka", "kain perban yang tipis", "Sinonim: kain kasa"],
  ["tensi", "tekanan darah dalam tubuh", "ukuran tekanan darah", "Sinonim: tekanan darah"],
  ["herbal", "obat dari tumbuhan", "bahan alami dari tanaman", "Sinonim: obat alami"],
  ["jamu", "obat tradisional Indonesia", "ramuan herbal untuk kesehatan", "Sinonim: obat tradisional"],
  ["senam", "olahraga dengan gerakan badan", "latihan tubuh berirama", "Sinonim: olahraga ringan"],
  ["yoga", "olahraga pernapasan dan peregangan", "latihan keseimbangan badan", "Sinonim: senam yoga"],
  ["lelap", "tidur yang nyenyak", "tertidur pulas", "Sinonim: nyenyak"],
  ["kudapan", "makanan ringan di antara waktu makan", "cemilan kecil", "Sinonim: camilan"],
  ["gasing", "mainan yang berputar", "mainan yang diputar dengan tali", "Sinonim: gangsing"],
  ["engklek", "permainan lompat satu kaki di kotak", "permainan tradisional di tanah", "Sinonim: permainan engklek"],
  ["umpet", "permainan sembunyi-sembunyian", "bersembunyi dari yang mencari", "Sinonim: petak umpet"],
  ["besan", "orang tua dari menantu", "hubungan dua keluarga karena pernikahan", "Sinonim: keluarga besan"],
  ["ipar", "saudara dari suami atau istri", "adik atau kakak pasangan", "Sinonim: saudara ipar"],
  ["cucu", "anak dari anak kita", "keturunan generasi kedua", "Sinonim: anak dari anak"],
  ["buyut", "anak dari cucu kita", "keturunan generasi keempat", "Sinonim: cicit dari kakek"],
  ["cicit", "anak dari buyut", "keturunan generasi kelima", "Sinonim: generasi kelima"],
  ["tiri", "bukan saudara kandung", "hubungan dari pernikahan ulang", "Sinonim: bukan kandung"],
  ["janin", "bayi yang masih di dalam kandungan", "calon bayi dalam perut ibu", "Sinonim: calon bayi"],
  ["lebaran", "hari raya setelah puasa", "hari kemenangan umat muslim", "Sinonim: idul fitri"],
  ["mudik", "pulang ke kampung saat hari raya", "perjalanan pulang kampung", "Sinonim: pulang kampung"],
  ["haji", "ibadah ke tanah suci", "rukun islam yang kelima", "Sinonim: naik haji"],
  ["puasa", "menahan makan dan minum", "ibadah di bulan ramadan", "Antonim: berbuka"],
  ["bedak", "bubuk halus untuk wajah", "kosmetik yang dipakai setelah cuci muka", "Sinonim: talk"],
  ["sampo", "cairan pembersih rambut", "yang dipakai saat keramas", "Sinonim: syampu"],
  ["pinset", "alat penjepit kecil yang runcing", "alat untuk mencabut duri", "Sinonim: penjepit kecil"],
  ["kikir", "alat untuk meratakan kuku", "alat pengasah yang bergerigi halus", "Sinonim: alat kikir"],
  ["kumur", "berkumur dengan air di mulut", "membersihkan mulut dengan air", "Sinonim: berkumur"],
  ["tambal", "menutup lubang dengan bahan", "memperbaiki ban bocor", "Sinonim: menambal"],
  ["jerigen", "wadah plastik besar bertutup", "tempat menyimpan minyak atau bensin", "Sinonim: jeriken"],
  ["talam", "wadah ceper untuk menyajikan", "nampan bundar dari logam", "Sinonim: nampan"],
  ["dulang", "wadah ceper untuk makanan", "talam besar dari kayu", "Sinonim: talam besar"],
  ["pemarut", "alat untuk memarut", "alat penghalus kelapa", "Sinonim: parutan"],
  ["jepitan", "alat untuk menjepit", "penjepit baju di jemuran", "Sinonim: jepit"],
  ["spanduk", "kain panjang berisi tulisan", "banner yang dipasang di jalan", "Sinonim: banner"],
  ["baliho", "papan besar berisi iklan", "reklame berukuran raksasa", "Sinonim: papan reklame"],
  ["reklame", "iklan yang dipasang di tempat umum", "pengumuman untuk menarik perhatian", "Sinonim: iklan"],
  ["plakat", "papan penghargaan yang dipajang", "tanda kenang-kenangan dari logam", "Sinonim: piagam"],
  ["piagam", "surat resmi sebagai tanda penghargaan", "sertifikat penghargaan", "Sinonim: sertifikat"],
  ["rapor", "laporan nilai belajar siswa", "buku nilai yang dibawa pulang", "Sinonim: laporan nilai"],
  ["cerpen", "cerita pendek dalam satu kali baca", "karangan fiksi yang singkat", "Sinonim: cerita pendek"],
  ["pamflet", "selebaran berisi informasi", "kertas kecil berisi pengumuman", "Sinonim: selebaran"],
  ["kuartet", "kelompok yang berjumlah empat", "tampil berempat", "Sinonim: berempat"],
  ["colokan", "tempat memasukkan steker", "lubang listrik di dinding", "Sinonim: stopkontak"],
  ["saklar", "alat untuk menyalakan dan mematikan lampu", "tombol listrik di dinding", "Sinonim: sakelar"],
  ["steker", "ujung kabel yang dicolokkan", "penghubung listrik ke stopkontak", "Sinonim: colokan"],
  ["dinamo", "mesin penghasil listrik", "pembangkit tenaga listrik kecil", "Sinonim: generator"],
  ["rambu", "tanda di jalan untuk pengemudi", "papan petunjuk lalu lintas", "Sinonim: rambu-rambu"],
  ["kelurahan", "wilayah pemerintahan di bawah kecamatan", "kantor pemerintahan tingkat desa", "Sinonim: desa kota"],
  ["kecamatan", "wilayah di atas kelurahan", "tingkat pemerintahan di bawah kabupaten", "Sinonim: camat"],
  ["puskesmas", "klinik kesehatan milik pemerintah", "tempat berobat di kecamatan", "Sinonim: klinik kesehatan"],
  ["posyandu", "layanan kesehatan balita di desa", "tempat imunisasi anak", "Sinonim: pos pelayanan terpadu"],
  ["periksa", "memeriksa dengan teliti", "kegiatan dokter melihat pasien", "Sinonim: memeriksa"],
  ["usungan", "alat untuk membawa orang sakit", "tandu untuk mengangkut pasien", "Sinonim: tandu"],
  ["berobat", "pergi ke dokter karena sakit", "mencari kesembuhan ke klinik", "Sinonim: berikhtiar"],
  ["tipes", "penyakit demam akibat bakteri", "sakit demam yang lama", "Sinonim: tifus"],
  ["gondongan", "penyakit bengkak di leher", "pipi membengkak karena virus", "Sinonim: parotitis"],
  ["cangkok", "menyambung tanaman baru", "cara menanam dengan menempel", "Sinonim: okulasi"],
  ["difabel", "orang dengan keterbatasan fisik", "penyandang disabilitas", "Sinonim: disabilitas"],
  ["mencret", "buang air besar terus-menerus", "perut sakit karena diare", "Sinonim: diare"],
  ["penganan", "makanan ringan atau kue", "camilan tradisional", "Sinonim: kudapan"],
  ["bedong", "kain pembungkus bayi", "selimut yang melilit bayi", "Sinonim: lampin"],
  ["kemenakan", "anak dari saudara", "keponakan", "Sinonim: keponakan"],
  ["jagoan", "orang yang diandalkan", "juara dalam pertarungan", "Sinonim: juara"],
  ["gangsing", "mainan kayu yang berputar", "mainan diputar dengan tali", "Sinonim: gasing"],
  ["yodium", "zat yang ada di garam beryodium", "unsur untuk mencegah gondok", "Sinonim: iodin"],
  ["taufan", "angin kencang yang berputar", "badai yang sangat kuat", "Sinonim: angin topan"],
  ["siklon", "badai angin yang berputar", "angin kencang di daerah tropis", "Sinonim: topan"],
  ["kaldera", "kawah gunung yang sangat luas", "cekungan besar di puncak gunung", "Sinonim: kawah besar"],
  ["geyser", "sumber air panas yang menyembur", "air panas memancar dari tanah", "Sinonim: mata air panas"],
  ["sabana", "padang rumput yang luas", "lahan rumput dengan pohon jarang", "Sinonim: savana"],
  ["sendang", "sumber air di desa", "mata air yang dikeramatkan", "Sinonim: mata air"],
  ["genangan", "air yang mengumpul di tanah", "air tergenang setelah hujan", "Sinonim: becek"],
  ["pancaroba", "pergantian musim kemarau ke hujan", "masa cuaca tidak menentu", "Sinonim: musim pancaroba"],
  ["penghujan", "musim banyak turun hujan", "waktu hujan turun terus", "Antonim: kemarau"],
  ["maghrib", "waktu matahari terbenam", "waktu salat setelah matahari tenggelam", "Sinonim: senja"],
  ["adzan", "seruan untuk salat", "panggilan masuk waktu salat", "Sinonim: azan"],
  ["kumandang", "suara yang bergema", "gema suara yang terdengar jauh", "Sinonim: gema"],
  ["weker", "jam yang berdering keras", "alarm untuk membangunkan tidur", "Sinonim: jam beker"],
  ["kabisat", "tahun yang bulan februari 29 hari", "tahun dengan hari tambahan", "Sinonim: tahun kabisat"],
  ["windu", "satuan waktu delapan tahun", "periode delapan tahun", "Sinonim: delapan tahun"],
  ["fuchsia", "warna merah keunguan cerah", "warna seperti bunga fuchsia", "Sinonim: magenta"],
  ["marun", "warna merah tua kecokelatan", "warna merah anggur tua", "Sinonim: maroon"],
  ["legam", "hitam sangat pekat", "warna hitam pekat", "Sinonim: hitam legam"],
  ["metalik", "berkilau seperti logam", "warna atau efek seperti besi", "Sinonim: kilau logam"],
  ["alumunium", "logam ringan berwarna perak", "bahan untuk membuat panci", "Sinonim: aluminium"],
  ["platina", "logam mulia berwarna putih", "logam mahal untuk perhiasan", "Sinonim: platinum"],
  ["ametis", "batu permata berwarna ungu", "batu ungu untuk perhiasan", "Sinonim: batu kecubung"],
  ["kuarsa", "mineral bening yang keras", "bahan utama membuat kaca", "Sinonim: kristal kuarsa"],
  ["batubara", "bahan bakar fosil berwarna hitam", "batu yang bisa terbakar untuk energi", "Sinonim: batu bara"],
  ["briket", "bahan bakar padat dari arang", "arang yang dipadatkan", "Sinonim: arang briket"],
  ["knalpot", "pipa pembuang asap kendaraan", "bagian motor yang mengeluarkan bunyi", "Sinonim: pipa knalpot"],
  ["lembab", "mengandung air atau uap air", "tidak kering", "Antonim: kering"],
  ["curah", "banyaknya air hujan yang turun", "jumlah hujan dalam satu daerah", "Sinonim: curah hujan"],
  ["neutron", "partikel tanpa muatan di dalam atom", "bagian inti atom yang netral", "Sinonim: partikel netral"],
  ["astronot", "orang yang pergi ke luar angkasa", "awak pesawat luar angkasa", "Sinonim: antariksawan"],
  ["atmosfir", "lapisan udara yang menyelimuti bumi", "udara di sekitar planet", "Sinonim: atmosfer"],
  ["akustik", "berhubungan dengan bunyi", "ilmu tentang suara", "Sinonim: ilmu bunyi"],
  ["leksikon", "kamus atau daftar kata", "kumpulan kosakata suatu bahasa", "Sinonim: kamus"],
  ["ironi", "sindiran halus dengan makna berkebalikan", "kata yang maknanya berlawanan dengan maksud", "Sinonim: sindiran"],
  ["kritikan", "tanggapan yang menilai kekurangan", "masukan tentang sesuatu", "Sinonim: kritik"],
  ["resensi", "ulasan tentang buku atau film", "tulisan penilaian karya", "Sinonim: ulasan"],
  ["kaidah", "aturan yang menjadi patokan", "pedoman yang harus diikuti", "Sinonim: aturan"],
  ["seminar", "pertemuan untuk membahas suatu ilmu", "diskusi para ahli di suatu bidang", "Sinonim: simposium"],
  ["pemilu", "pemilihan umum untuk memilih pemimpin", "pesta demokrasi memilih wakil rakyat", "Sinonim: pemilihan umum"],
  ["silabus", "rencana pembelajaran di sekolah", "daftar materi pelajaran", "Sinonim: rencana pelajaran"],
  ["prosa", "karangan bebas yang bukan puisi", "tulisan berbentuk cerita", "Sinonim: karangan"],
  ["hikayat", "cerita lama yang mengisahkan raja", "kisah kepahlawanan zaman dulu", "Sinonim: riwayat"],
  ["fabel", "cerita binatang yang berperilaku manusia", "dongeng dengan tokoh hewan", "Sinonim: cerita binatang"],
  ["tamasya", "bepergian untuk bersenang-senang", "jalan-jalan menikmati pemandangan", "Sinonim: piknik"],
  ["imlek", "tahun baru masyarakat Tionghoa", "hari raya dengan angpau merah", "Sinonim: tahun baru cina"],
  ["waisak", "hari raya umat Buddha", "peringatan kelahiran sang Buddha", "Sinonim: hari raya Buddha"],
  ["mapel", "mata pelajaran di sekolah", "bidang ilmu yang diajarkan", "Sinonim: mata pelajaran"],
  ["prodi", "program studi di perguruan tinggi", "jurusan di universitas", "Sinonim: jurusan kuliah"],
  ["ponsel", "telepon genggam", "telepon yang bisa dibawa ke mana-mana", "Sinonim: telepon seluler"],
  ["gawai", "perangkat elektronik canggih", "alat seperti telepon pintar", "Sinonim: gadget"],
  ["internet", "jaringan komputer di seluruh dunia", "jaringan yang menghubungkan semua orang", "Sinonim: daring"],
  ["swafoto", "foto diri sendiri", "memotret wajah sendiri", "Sinonim: selfie"],
  ["obyek", "benda atau hal yang menjadi sasaran", "sesuatu yang diamati", "Sinonim: objek"],
  ["seblak", "makanan pedas khas Bandung", "kerupuk basah yang dimasak pedas", "Sinonim: cilok pedas"],
  ["dimsum", "makanan kukus khas Tionghoa", "pangsit kukus berbagai isi", "Sinonim: siomay"],
  ["gudeg", "makanan manis khas Yogyakarta", "nangka muda yang dimasak santan", "Sinonim: gudeg jogja"],
  ["pecel", "sayur rebus dengan sambal kacang", "makanan khas dengan bumbu kacang", "Sinonim: pecel sayur"],
  ["pedati", "gerobak yang ditarik kuda", "kereta beroda kayu di desa", "Sinonim: gerobak kuda"],
  ["kontainer", "peti besi besar untuk angkutan", "kotak raksasa pengangkut barang", "Sinonim: peti kemas"],
  ["kebakaran", "peristiwa api membakar bangunan", "kejadian dilalap api", "Sinonim: kebakaran hutan"],
  ["sedan", "mobil tertutup berempat pintu", "mobil penumpang yang nyaman", "Sinonim: mobil sedan"],
  ["minibus", "bus kecil untuk penumpang sedikit", "mobil angkutan ukuran kecil", "Sinonim: angkot"],
  ["komuter", "penumpang kereta harian", "orang yang pulang pergi bekerja", "Sinonim: penumpang harian"],
  ["monorel", "kereta yang berjalan di satu rel", "kereta gantung di jalur tunggal", "Sinonim: kereta rel tunggal"],
  ["trottoar", "jalan khusus untuk pejalan kaki", "trotoar di pinggir jalan", "Sinonim: trotoar"],
  ["barcode", "kode garis hitam putih pada produk", "kode yang dipindai di kasir", "Sinonim: kode batang"],
  ["debit", "uang yang keluar dari rekening", "pengurangan saldo bank", "Antonim: kredit"],
  ["cicilan", "pembayaran dengan angsuran", "bayar sedikit demi sedikit", "Sinonim: angsuran"],
  ["hutang", "uang yang harus dibayar kembali", "pinjaman yang belum dilunasi", "Sinonim: utang"],
  ["piutang", "uang yang dipinjamkan ke orang lain", "tagihan yang harus diterima", "Antonim: hutang"],
  ["kwitansi", "surat bukti pembayaran", "tanda terima uang", "Sinonim: struk"],
  ["struk", "kertas bukti transaksi", "bukti belanja dari kasir", "Sinonim: nota"],
  ["wirausaha", "orang yang menjalankan usaha sendiri", "pengusaha mandiri", "Sinonim: pengusaha"],
  ["sedekah", "pemberian sukarela kepada yang membutuhkan", "memberi tanpa mengharap balasan", "Sinonim: derma"],
  ["zakat", "harta yang wajib dikeluarkan umat islam", "pemberian wajib setiap tahun", "Sinonim: zakat fitrah"],
  ["infak", "pemberian harta di jalan kebaikan", "sumbangan sukarela", "Sinonim: sumbangan"],
  ["wakaf", "harta yang disumbangkan untuk umum", "tanah yang dihibahkan untuk masjid", "Sinonim: hibah"],
  ["relawan", "orang yang bekerja tanpa upah", "sukarelawan untuk kemanusiaan", "Sinonim: sukarelawan"],
  ["bolos", "tidak masuk tanpa izin", "membolos sekolah", "Sinonim: kabur"],
  ["jenjang", "tingkatan yang berurutan", "tangga kepangkatan", "Sinonim: tingkatan"],
  ["karir", "perjalanan pekerjaan seseorang", "jenjang pekerjaan", "Sinonim: karier"],
  ["capaian", "hasil yang sudah diraih", "prestasi yang dicapai", "Sinonim: prestasi"],
  ["finalis", "peserta yang masuk babak akhir", "yang bertanding di final", "Sinonim: peserta akhir"],
  ["nomine", "calon pemenang penghargaan", "yang dicalonkan untuk menang", "Sinonim: kandidat"],
  ["estafet", "lari berantai membawa tongkat", "lomba lari sambung", "Sinonim: lari sambung"],
  ["galah", "tongkat panjang untuk menolak lompat", "alat lompat tinggi dengan tongkat", "Sinonim: tongkat lompat"],
  ["lembing", "tombak untuk olahraga lempar", "alat lempar dalam atletik", "Sinonim: tombak"],
  ["cakram", "piringan yang dilempar dalam atletik", "alat lempar berbentuk piring", "Sinonim: piringan lempar"],
  ["lontar", "melemparkan dengan tangan", "tolak peluru dalam olahraga", "Sinonim: lempar"],
  ["martil", "palu besar untuk olahraga lempar", "bola besi bertali untuk dilempar", "Sinonim: palu besar"],
  ["kiper", "penjaga gawang dalam sepak bola", "pemain yang menangkap bola", "Sinonim: penjaga gawang"],
  ["cadangan", "pemain pengganti di pertandingan", "yang disiapkan bila pemain utama absen", "Sinonim: pengganti"],
  ["skuad", "rombongan pemain satu tim", "daftar pemain sebuah klub", "Sinonim: tim"],
  ["tangkis", "menangkis pukulan lawan", "memukul bola ke arah lawan", "Sinonim: menangkis"],
  ["silat", "olahraga bela diri khas Indonesia", "pencak silat dari nusantara", "Sinonim: pencak"],
  ["pencak", "gerakan bela diri Indonesia", "seni bela diri berirama", "Sinonim: silat"],
  ["ritmik", "berhubungan dengan irama", "senam dengan gerakan berirama", "Sinonim: berirama"],
  ["aerobik", "olahraga dengan gerakan mengikuti irama", "senam yang membuat jantung berdebar", "Sinonim: senam aerobik"],
  ["hompimpa", "undian dengan telapak tangan", "cara menentukan giliran main", "Sinonim: pingsut"],
  ["tandang", "bertanding di kandang lawan", "pergi ke tempat lawan", "Antonim: kandang"],
  ["sebelas", "angka setelah sepuluh", "jumlah jari dua tangan dan satu lagi", "Sinonim: sebelas"],
  ["skalar", "besaran yang hanya punya nilai", "besaran tanpa arah", "Antonim: vektor"],
  ["besaran", "sesuatu yang bisa diukur", "nilai seperti panjang dan berat", "Sinonim: ukuran"],
  ["lustrum", "periode lima tahun", "masa lima tahunan", "Sinonim: lima tahun"],
  ["pelopor", "orang yang memulai sesuatu lebih dulu", "perintis suatu gerakan", "Sinonim: perintis"],
  ["figur", "orang yang menjadi contoh", "tokoh yang berpengaruh", "Sinonim: tokoh"],
  ["karakter", "sifat atau watak seseorang", "kepribadian yang khas", "Sinonim: watak"],
  ["watak", "sifat batin yang mempengaruhi perilaku", "tabiat seseorang", "Sinonim: karakter"],
  ["tabiat", "kelakuan yang sudah menjadi kebiasaan", "sifat bawaan seseorang", "Sinonim: watak"],
  ["pekerti", "perilaku dan budi pekerti", "sopan santun dalam bertingkah laku", "Sinonim: budi pekerti"],
  ["akhlak", "tingkah laku yang baik", "perangai dan budi pekerti", "Sinonim: moral"],
  ["lazim", "sudah biasa terjadi", "umum dilakukan orang", "Sinonim: umum"],
  ["hakikat", "inti atau dasar dari sesuatu", "kenyataan yang sebenarnya", "Sinonim: inti"],
  ["faedah", "manfaat dari sesuatu", "kegunaan suatu hal", "Sinonim: manfaat"],
  ["setuju", "sepakat dengan pendapat orang lain", "menyatakan iya atas usulan", "Sinonim: sepakat"],
  ["dusun", "bagian desa yang terpencil", "kampung kecil di pedalaman", "Sinonim: kampung"],
  ["bergizi", "mengandung zat makanan yang baik", "kaya akan vitamin dan protein", "Sinonim: bernutrisi"],
  ["tumpeng", "nasi berbentuk kerucut untuk acara", "nasi kuning untuk selamatan", "Sinonim: nasi tumpeng"],
  ["jajanan", "makanan ringan di sekolah", "camilan yang dijual di pasar", "Sinonim: camilan"],
  ["etiket", "tata cara sopan dalam pergaulan", "aturan berperilaku yang baik", "Sinonim: sopan santun"],
  ["cipta", "membuat sesuatu yang baru", "menciptakan karya", "Sinonim: mencipta"],
  ["absah", "sah menurut hukum", "resmi dan diakui", "Sinonim: sah"],
  ["rampung", "selesai dikerjakan", "tuntas sampai akhir", "Sinonim: selesai"],
  ["tegap", "tegak dan kokoh tubuhnya", "berdiri lurus dengan gagah", "Sinonim: gagah"],
  ["bugar", "sehat dan segar badan", "tubuh dalam kondisi prima", "Sinonim: segar"],
  ["latihan", "kegiatan untuk mengasah kemampuan", "berlatih sebelum bertanding", "Sinonim: berlatih"],
  ["bisul", "bengkak berisi nanah di kulit", "jerawat besar yang bernanah", "Sinonim: barah"],
  ["komedo", "titik hitam di pori kulit", "kotoran yang menyumbat pori", "Sinonim: jerawat hitam"],
  ["bercak", "noda atau bekas di permukaan", "titik kotor pada kulit", "Sinonim: noda"],
  ["pangkal", "bagian awal dari sesuatu", "tempat dimulainya batang", "Antonim: ujung"],
  ["terkilir", "keseleo pada sendi", "salah urat karena gerakan tiba-tiba", "Sinonim: keseleo"],
  ["kapalan", "kulit menebal karena gesekan", "tangan keras karena bekerja", "Sinonim: keras kulit"],
  ["cantengan", "kuku yang tumbuh ke dalam daging", "jari sakit karena kuku menusuk", "Sinonim: kuku tumbuh"],
  ["melepuh", "kulit menggelembung karena panas", "terbakar sehingga timbul gelembung", "Sinonim: melepuh"],
  ["berjuang", "berusaha keras mencapai tujuan", "berkorban untuk sesuatu", "Sinonim: berikhtiar"],
  ["respons", "tanggapan atas sesuatu", "reaksi terhadap rangsangan", "Sinonim: tanggapan"],
  ["rangkuman", "ringkasan dari suatu bacaan", "inti dari pembicaraan", "Sinonim: ringkasan"],
  ["simpulan", "pendapat akhir dari pembahasan", "hasil akhir suatu penalaran", "Sinonim: kesimpulan"],
  ["intisari", "bagian terpenting dari sesuatu", "sari dari sebuah cerita", "Sinonim: sari"],
  ["ringkas", "tidak panjang dan tidak bertele-tele", "singkat dan jelas", "Sinonim: singkat"],
  ["total", "jumlah seluruhnya", "keseluruhan tanpa kecuali", "Sinonim: seluruh"],
  ["gurau", "perkataan yang tidak sungguhan", "canda dan senda gurau", "Sinonim: canda"],
  ["viral", "menyebar dengan cepat di internet", "menjadi terkenal seketika", "Sinonim: terkenal"],
  ["tenar", "dikenal banyak orang", "terkenal di mana-mana", "Sinonim: terkenal"],
  ["lestari", "tetap ada dan tidak punah", "terjaga selamanya", "Sinonim: kekal"],
  ["monoton", "itu-itu saja dan membosankan", "tidak ada variasi", "Sinonim: datar"],
  ["sesal", "rasa menyesal atas perbuatan", "penyesalan karena keliru", "Sinonim: penyesalan"],
  ["melamun", "berpikir melayang jauh", "berangan-angan tidak sadar", "Sinonim: berkhayal"],
  ["sejenak", "sebentar saja", "berhenti sesaat", "Sinonim: sesaat"],
  ["berazam", "berniat dengan tekad kuat", "bertekad bulat", "Sinonim: bertekad"],
  ["pahala", "balasan kebaikan dari tuhan", "ganjaran atas perbuatan baik", "Sinonim: ganjaran"],
  ["umrah", "ibadah ke tanah suci di luar musim haji", "ziarah ke baitullah", "Sinonim: haji kecil"],
  ["qurban", "menyembelih hewan di hari raya", "berkurban untuk berbagi daging", "Sinonim: kurban"],
  ["walimah", "perayaan pernikahan", "pesta resepsi pengantin", "Sinonim: resepsi"],
  ["talak", "perceraian dalam pernikahan", "putusnya ikatan suami istri", "Sinonim: cerai"],
  ["bujang", "laki-laki yang belum menikah", "lajang", "Sinonim: lajang"],
  ["galau", "perasaan gelisah dan bingung", "hati tidak tenang", "Sinonim: resah"],
  ["dalih", "alasan untuk menghindari kenyataan", "berdalih untuk menutupi", "Sinonim: alasan"],
  ["bimbingan", "tuntunan untuk mengarahkan", "pengarahan dari pembimbing", "Sinonim: arahan"],
  ["progres", "kemajuan dari suatu pekerjaan", "perkembangan ke arah lebih baik", "Sinonim: kemajuan"],
  ["inovasi", "penemuan baru yang bermanfaat", "pembaruan dari yang lama", "Sinonim: pembaruan"],
  ["kreasi", "hasil karya ciptaan", "sesuatu yang dibuat dengan imajinasi", "Sinonim: ciptaan"],
  ["kangen", "rindu yang mendalam", "ingin bertemu seseorang", "Sinonim: rindu"],
  ["nalar", "kemampuan berpikir logis", "akal sehat dalam menimbang", "Sinonim: logika"],
  ["nyambung", "berhubungan satu sama lain", "jawaban yang berkesinambungan", "Sinonim: berhubungan"],
  ["kalut", "kacau dan tidak menentu", "pikiran yang kusut", "Sinonim: kacau"],
  ["antre", "berbaris menunggu giliran", "mengantri di loket", "Sinonim: mengantre"],
  ["antrean", "barisan orang yang menunggu", "deretan pembeli di kasir", "Sinonim: barisan"],
  ["bergilir", "secara bergantian", "berurutan satu per satu", "Sinonim: bergantian"],
  ["mujur", "beruntung dalam keadaan", "nasib baik", "Sinonim: beruntung"],
  ["melayat", "menjenguk keluarga yang berduka", "pergi ke rumah duka", "Sinonim: bertakziah"],
  ["takziah", "ucapan belasungkawa", "kunjungan menghibur keluarga duka", "Sinonim: belasungkawa"],
  ["nonton", "menonton pertunjukan atau film", "menyaksikan tayangan", "Sinonim: menonton"],
  ["animasi", "gambar bergerak untuk film", "kartun yang digambar berurutan", "Sinonim: kartun"],
];
