-- ============================================================
-- KotaKata AI — Vocabulary (soal / pertanyaan)
-- Generated from src/data/sources/vocabularySeed.ts
-- Total: 270 words across 10 tiers
-- ============================================================

create table if not exists public.vocabulary (
  word_id    text primary key,
  word       text not null,
  clue_1     text not null,
  clue_2     text,
  clue_3     text,
  tier_level int  not null default 1,
  created_at timestamptz not null default now()
);

insert into public.vocabulary (word_id, word, clue_1, clue_2, clue_3, tier_level) values
  ('t1-001', 'API', 'Panas yang membakar', 'Sumber nyala berwarna merah jingga', 'Diawali dengan huruf A, fenomena alam yang menghasilkan panas', 1),
  ('t1-002', 'AIR', 'Cairan yang kita minum', 'Zat bening tidak berwarna', 'Huruf depannya A, diperlukan semua makhluk hidup', 1),
  ('t1-003', 'BUKU', 'Benda yang dibaca', 'Kumpulan kertas berisi tulisan', 'Diawali B, terdiri dari 4 huruf, teman belajar', 1),
  ('t1-004', 'AKU', 'Diri sendiri', 'Kata ganti orang pertama', 'Terdiri dari 3 huruf, dimulai dengan A', 1),
  ('t1-005', 'MATA', 'Alat penglihatan', 'Bagian wajah untuk melihat', '4 huruf, dimulai M, ada di kepala', 1),
  ('t1-006', 'KAKI', 'Bagian tubuh untuk berjalan', 'Anggota gerak bawah', '4 huruf, dimulai K, ada sepasang', 1),
  ('t1-007', 'TANG', 'Alat untuk menjepit', 'Peralatan pertukangan', '4 huruf, sering dipakai tukang', 1),
  ('t1-008', 'PINTU', 'Celah untuk keluar masuk', 'Bukaan pada dinding rumah', '5 huruf, biasanya ada gagangnya', 1),
  ('t1-009', 'RUMAH', 'Tempat tinggal', 'Bangunan untuk berlindung', '5 huruf, dimulai R, tempat keluarga', 1),
  ('t1-010', 'BOLA', 'Benda bulat untuk main', 'Alat olahraga berbentuk bundar', '4 huruf, ditendang atau dilempar', 1),
  ('t1-011', 'GARIS', 'Coretan memanjang', 'Tanda berbentuk lurus', '5 huruf, bisa lurus atau melengkung', 1),
  ('t1-012', 'HUJAN', 'Air yang turun dari langit', 'Fenomena cuaca basah', '5 huruf, biasanya bikin basah', 1),
  ('t1-013', 'IKAN', 'Hewan yang hidup di air', 'Binatang bersisik', '4 huruf, berenang pakai sirip', 1),
  ('t1-014', 'JALAN', 'Tempat kendaraan lewat', 'Lintasan untuk berjalan', '5 huruf, aspal atau beton', 1),
  ('t1-015', 'KURSI', 'Tempat duduk', 'Perabot untuk diduduki', '5 huruf, biasanya berkaki empat', 1),
  ('t1-016', 'LANGIT', 'Ruang di atas bumi', 'Tempat awan dan matahari', '6 huruf, berwarna biru di siang hari', 1),
  ('t1-017', 'MEJA', 'Tempat meletakkan barang', 'Perabot permukaan datar', '4 huruf, tempat belajar atau makan', 1),
  ('t1-018', 'NASI', 'Makanan pokok orang Indonesia', 'Beras yang sudah dimasak', '4 huruf, dimakan setiap hari', 1),
  ('t1-019', 'POHON', 'Tumbuhan besar', 'Tanaman berkayu tinggi', '5 huruf, punya batang dan daun', 1),
  ('t1-020', 'SAPI', 'Hewan yang menghasilkan susu', 'Binatang ternak bertanduk', '4 huruf, berkaki empat', 1),
  ('t1-021', 'TELUR', 'Benda bulat yang menetas', 'Hasil unggas berbentuk oval', '5 huruf, bisa diceplok atau direbus', 1),
  ('t1-022', 'ULAR', 'Hewan melata tidak berkaki', 'Binatang panjang berbisa', '4 huruf, bergerak meliuk-liuk', 1),
  ('t1-023', 'BATU', 'Benda padat keras', 'Material alam yang keras', '4 huruf, biasanya di sungai', 1),
  ('t1-024', 'DAUN', 'Bagian hijau tumbuhan', 'Organ fotosintesis tanaman', '4 huruf, tumbuh di ranting', 1),
  ('t1-025', 'EMAS', 'Logam mulia berwarna kuning', 'Bahan perhiasan berkilau', '4 huruf, sangat berharga', 1),
  ('t1-026', 'GUNUNG', 'Bukit yang sangat tinggi', 'Tinggian alam yang besar', '6 huruf, ada yang masih aktif', 1),
  ('t1-027', 'HUTAN', 'Tempat banyak pohon', 'Kawasan rimba belantara', '5 huruf, rumah bagi satwa liar', 1),
  ('t1-028', 'INDAH', 'Sesuatu yang elok dipandang', 'Mempunyai keelokan', '5 huruf, lawan dari jelek', 1),
  ('t1-029', 'JEMUR', 'Menjemur pakaian di panas', 'Mengeringkan dengan sinar matahari', '5 huruf, dilakukan di siang hari', 1),
  ('t1-030', 'KUMAN', 'Makhluk kecil penyebab penyakit', 'Bakteri yang tidak kasatmata', '5 huruf, perlu mikroskop untuk lihat', 1),
  ('t1-031', 'MINTA', 'Memohon sesuatu', 'Mengemukakan keinginan', '5 huruf, lawan dari memberi', 1),
  ('t1-032', 'ORANG', 'Manusia', 'Individu dari spesies homo sapiens', '5 huruf, makhluk sosial', 1),
  ('t1-033', 'PASIR', 'Butiran halus di pantai', 'Material kecil dari bebatuan', '5 huruf, biasanya di pantai atau sungai', 1),
  ('t1-034', 'RANTAI', 'Sambungan lingkaran besi', 'Benda dari cincin yang saling berkait', '6 huruf, digunakan untuk mengikat', 1),
  ('t1-035', 'SUNYI', 'Sepi tidak bersuara', 'Tanpa keramaian', '5 huruf, tidak ada suara apapun', 1),
  ('t1-036', 'TEBAL', 'Tidak tipis', 'Mempunyai ukuran antar permukaan besar', '5 huruf, lawan dari tipis', 1),
  ('t1-037', 'UPAC', 'Anak katak', 'Berudu yang baru metamorfosis', '4 huruf, hewan kecil berkaki empat', 1),
  ('t1-038', 'WARNA', 'Corak pada benda', 'Spektrum cahaya yang terlihat', '5 huruf, ada merah, biru, hijau', 1),
  ('t1-039', 'YAKIN', 'Percaya sepenuh hati', 'Tidak ragu-ragu', '5 huruf, yakin itu percaya', 1),
  ('t1-040', 'ZAKAT', 'Kewajiban bagi umat Islam', 'Memberikan sebagian harta', '5 huruf, salah satu rukun Islam', 1),
  ('t1-041', 'LEBIH', 'Bertambah banyak', 'Melebihi jumlah tertentu', '5 huruf, lawan dari kurang', 1),
  ('t1-042', 'DAGING', 'Bagian tubuh hewan yang dimakan', 'Lunak di antara tulang dan kulit', '6 huruf, sumber protein', 1),
  ('t1-043', 'CEPAT', 'Lawan dari lambat', 'Memiliki kecepatan tinggi', '5 huruf, kalo lari nggak lambat', 1),
  ('t1-044', 'BENAR', 'Tidak salah', 'Sesuai dengan kebenaran', '5 huruf, lawan dari salah', 1),
  ('t1-045', 'TULIS', 'Membuat huruf di kertas', 'Menuangkan ide dalam bentuk teks', '5 huruf, pakai pensil atau pulpen', 1),
  ('t1-046', 'SEMUT', 'Serangga kecil pekerja keras', 'Hewan kecil yang hidup berkoloni', '5 huruf, suka mengangkut gula', 1),
  ('t1-047', 'LAPAR', 'Ingin makan', 'Rasa saat perut kosong', '5 huruf, lawan dari kenyang', 1),
  ('t1-048', 'HAUS', 'Ingin minum', 'Rasa saat tenggorokan kering', '4 huruf, lawan dari kenyang minum', 1),
  ('t1-049', 'GIGI', 'Bagian mulut untuk mengunyah', 'Organ keras di dalam mulut', '4 huruf, ada yang putih dan kuning', 1),
  ('t1-050', 'HIDUNG', 'Alat penciuman', 'Bagian wajah yang menonjol', '6 huruf, gunanya buat cium bau', 1),
  ('t2-001', 'ANGIN', 'Udara yang bergerak', 'Aliran udara dari tekanan tinggi ke rendah', '5 huruf, tidak terlihat tapi terasa', 2),
  ('t2-002', 'BAYAM', 'Sayuran berdaun hijau', 'Tanaman yang kaya zat besi', '5 huruf, favoritnya Popeye', 2),
  ('t2-003', 'CERAH', 'Cuaca terang', 'Tidak mendung atau hujan', '5 huruf, langit tanpa awan', 2),
  ('t2-004', 'DAMAI', 'Tidak ada perang', 'Suasana tenteram dan tenang', '5 huruf, lawan dari perang', 2),
  ('t2-005', 'ELANG', 'Burung pemangsa', 'Unggas buas yang terbang tinggi', '5 huruf, punya penglihatan tajam', 2),
  ('t2-006', 'GEMUK', 'Badan besar berisi', 'Memiliki timbunan lemak', '5 huruf, lawan dari kurus', 2),
  ('t2-007', 'HARUM', 'Wanginya enak', 'Berbau sedap menyenangkan', '5 huruf, lawan dari bau busuk', 2),
  ('t2-008', 'KANAN', 'Arah lawan dari kiri', 'Sisi tubuh yang biasanya lebih kuat', '5 huruf, lawan dari kiri', 2),
  ('t2-009', 'LAUTAN', 'Air asin yang luas', 'Perairan yang membentang luas', '6 huruf, tempat kapal berlayar', 2),
  ('t2-010', 'MALAM', 'Waktu gelap setelah siang', 'Saat bulan dan bintang bersinar', '5 huruf, waktu untuk tidur', 2),
  ('t2-011', 'NENAS', 'Buah kuning bermahkota', 'Buah tropis yang asam manis', '5 huruf, kulitnya bersisik tajam', 2),
  ('t2-012', 'PISANG', 'Buah kuning melengkung', 'Buah yang enak dimakan langsung', '6 huruf, monyet suka ini', 2),
  ('t2-013', 'RAJIN', 'Suka bekerja keras', 'Tekun dan giat dalam bekerja', '5 huruf, lawan dari malas', 2),
  ('t2-014', 'SENANG', 'Perasaan gembira', 'Merasa bahagia dan puas', '6 huruf, lawan dari sedih', 2),
  ('t2-015', 'TAMAN', 'Kebun tempat bersantai', 'Lahan hijau untuk rekreasi', '5 huruf, ada bunga dan pohon', 2),
  ('t2-016', 'USANG', 'Sudah lama dan lapuk', 'Tidak baru lagi, ketinggalan zaman', '5 huruf, lawan dari baru', 2),
  ('t2-017', 'BARIS', 'Deretan lurus', 'Susunan memanjang sejajar', '5 huruf, antrean yang rapi', 2),
  ('t2-018', 'CINTA', 'Perasaan sayang yang kuat', 'Kasih terhadap sesama', '5 huruf, bahasa Inggrisnya love', 2),
  ('t2-019', 'DERAS', 'Aliran yang kencang', 'Cepat dan kuat (tentang arus)', '5 huruf, lawan dari pelan', 2),
  ('t2-020', 'GAJAH', 'Hewan darat terbesar', 'Mamalia berbelalai panjang', '5 huruf, punya gading', 2),
  ('t2-021', 'HITAM', 'Warna gelap pekat', 'Warna paling gelap', '5 huruf, lawan dari putih', 2),
  ('t2-022', 'JAGUNG', 'Sereal kuning berbiji', 'Tanaman pangan berbuah tongkol', '6 huruf, bisa dibakar atau direbus', 2),
  ('t2-023', 'KELAPA', 'Buah berkulit keras', 'Pohon serbaguna yang tumbuh di pantai', '6 huruf, ada air di dalamnya', 2),
  ('t2-024', 'LARANG', 'Tidak memperbolehkan', 'Memberi perintah untuk tidak melakukan', '6 huruf, lawan dari izin', 2),
  ('t2-025', 'MANGGA', 'Buah manis berwarna kuning', 'Buah tropis yang harum', '6 huruf, punya biji besar', 2),
  ('t2-026', 'PAGAR', 'Pembatas di sekeliling rumah', 'Struktur pemisah antar lahan', '5 huruf, bisa dari kayu atau besi', 2),
  ('t2-027', 'RONA', 'Warna di wajah', 'Air muka yang berseri', '4 huruf, pipi yang memerah', 2),
  ('t2-028', 'SABUN', 'Alat mandi yang berbusa', 'Pembersih berbentuk batang atau cair', '5 huruf, dipakai dengan air', 2),
  ('t2-029', 'TIRAM', 'Kerang penghasil mutiara', 'Hewan laut bercangkang', '5 huruf, hidup di laut', 2),
  ('t2-030', 'UNGKAP', 'Menyatakan sesuatu', 'Mengemukakan perasaan atau pikiran', '6 huruf, mengeluarkan isi hati', 2),
  ('t3-001', 'ALAMAT', 'Tempat tinggal seseorang', 'Informasi lokasi', '6 huruf, biasanya ada di KTP', 3),
  ('t3-002', 'BEBASKAN', 'Lepaskan dari ikatan', 'Memberi kemerdekaan', '8 huruf, memerdekakan seseorang', 3),
  ('t3-003', 'CEMBURU', 'Rasa iri saat pasangan dekat orang lain', 'Perasaan curiga terhadap kesetiaan', '7 huruf, emosi yang membara', 3),
  ('t3-004', 'DENDANG', 'Nyanyian khas daerah', 'Lagu dengan irama bersemangat', '7 huruf, dinyanyikan saat pesta', 3),
  ('t3-005', 'ERATKAN', 'Buat menjadi kuat hubungannya', 'Mengikat dengan kencang', '7 huruf, memperkuat ikatan', 3),
  ('t3-006', 'GELOMBANG', 'Gerakan air naik turun di laut', 'Ombak yang bergulung-gulung', '9 huruf, terjadi di permukaan air', 3),
  ('t3-007', 'HORMATI', 'Menghargai orang lain', 'Memberi penghargaan dan respek', '7 huruf, sikap sopan kepada yang lebih tua', 3),
  ('t3-008', 'ISOLASI', 'Memisahkan dari yang lain', 'Tindakan mengkarantina', '7 huruf, memisahkan diri dari keramaian', 3),
  ('t3-009', 'JENDERAL', 'Pangkat tertinggi di militer', 'Pemimpin angkatan bersenjata', '8 huruf, bintang di pundak', 3),
  ('t3-010', 'KISAHNYA', 'Cerita tentang seseorang', 'Riwayat hidup yang diceritakan', '8 huruf, narasi masa lalu', 3),
  ('t3-011', 'LEMBUT', 'Halus dan empuk', 'Tidak keras saat disentuh', '6 huruf, lawan dari kasar', 3),
  ('t3-012', 'MANISAN', 'Makanan atau minuman yang manis', 'Sesuatu yang diberi gula', '7 huruf, buah yang diawetkan', 3),
  ('t3-013', 'NIKMATI', 'Rasakan dengan senang', 'Menghayati kesenangan', '7 huruf, menikmati dengan sepenuh hati', 3),
  ('t3-014', 'PELUKAN', 'Dekapan kasih sayang', 'Memeluk dengan hangat', '7 huruf, gestur penuh cinta', 3),
  ('t3-015', 'RASAKAN', 'Cicipi dengan lidah', 'Alami dengan perasaan', '7 huruf, dirasakan dalam hati', 3),
  ('t3-016', 'SEMANGAT', 'Dorongan untuk berusaha', 'Energi positif dalam diri', '8 huruf, api yang membakar jiwa', 3),
  ('t3-017', 'TANGISAN', 'Air mata yang jatuh', 'Ekspresi duka dengan air mata', '8 huruf, mengeluarkan kesedihan', 3),
  ('t3-018', 'USAHAKU', 'Kerja keras yang kulakukan', 'Upaya untuk mencapai sesuatu', '7 huruf, demi meraih mimpi', 3),
  ('t3-019', 'BERKAT', 'Karunia yang diberikan Tuhan', 'Anugerah dalam kehidupan', '6 huruf, sesuatu yang diberkati', 3),
  ('t3-020', 'CERMIN', 'Benda yang memantulkan bayangan', 'Kaca untuk melihat diri sendiri', '6 huruf, introspeksi diri', 3),
  ('t3-021', 'DEWASA', 'Tidak anak-anak lagi', 'Tahap kehidupan setelah remaja', '6 huruf, sudah cukup umur', 3),
  ('t3-022', 'GEMBIRA', 'Perasaan suka cita', 'Riang dan penuh kegembiraan', '7 huruf, hati yang melonjak senang', 3),
  ('t3-023', 'HARAPAN', 'Sesuatu yang diinginkan', 'Keyakinan akan masa depan', '7 huruf, membuat hidup terus berjalan', 3),
  ('t3-024', 'ISTIMEWA', 'Sangat spesial', 'Lebih dari biasanya', '8 huruf, luar biasa dan unik', 3),
  ('t3-025', 'KETULUSAN', 'Keikhlasan hati', 'Sikap jujur tanpa pamrih', '9 huruf, kemurnian hati', 3),
  ('t3-026', 'MAKNA', 'Arti dari sesuatu', 'Substansi yang terkandung', '5 huruf, esensi dari kehidupan', 3),
  ('t3-027', 'NURANI', 'Suara hati', 'Hati yang murni', '6 huruf, bisikan batin yang jujur', 3),
  ('t3-028', 'SEJARAH', 'Kejadian di masa lalu', 'Riwayat peristiwa yang sudah terjadi', '7 huruf, kisah yang tercatat', 3),
  ('t3-029', 'TAULADAN', 'Teladan yang baik', 'Seseorang yang patut dicontoh', '8 huruf, panutan dalam kehidupan', 3),
  ('t3-030', 'BERTEMU', 'Bertemu seseorang', 'Bersua dengan orang lain', '7 huruf, tatap muka langsung', 3),
  ('t4-001', 'AKRAB', 'Hubungan yang dekat', 'Karib dan bersahabat', '5 huruf, intim dalam pertemanan', 4),
  ('t4-002', 'BERANI', 'Tidak takut', 'Memiliki keberanian menghadapi risiko', '6 huruf, lawan dari penakut', 4),
  ('t4-003', 'CANTIK', 'Indah dipandang', 'Mempesona secara visual', '6 huruf, elok rupawan', 4),
  ('t4-004', 'DIAM', 'Tidak bersuara', 'Sunyi tanpa kata', '4 huruf, emas katanya', 4),
  ('t4-005', 'ELOK', 'Indah dan molek', 'Cantik menawan', '4 huruf, pesona yang memikat', 4),
  ('t4-006', 'FIKIR', 'Aktivitas otak', 'Proses berpikir', '5 huruf, menggunakan akal', 4),
  ('t4-007', 'GELISAH', 'Tidak tenang', 'Merasa cemas dan was-was', '7 huruf, hati yang tak karuan', 4),
  ('t4-008', 'HENING', 'Sepi dan sunyi', 'Ketenangan tanpa suara', '6 huruf, suasana yang khusyuk', 4),
  ('t4-009', 'IBADAH', 'Pengabdian kepada Tuhan', 'Amalan spiritual yang dilakukan rutin', '6 huruf, kewajiban umat beragama', 4),
  ('t4-010', 'JUJUR', 'Berkata apa adanya', 'Sifat tidak berbohong', '5 huruf, sikap yang mulia', 4),
  ('t4-011', 'KARENA', 'Sebab atau alasan', 'Kata hubung yang menyatakan penyebab', '6 huruf, menandakan hubungan kausal', 4),
  ('t4-012', 'LAPANGAN', 'Tanah yang luas dan rata', 'Area terbuka untuk olahraga', '8 huruf, tempat bermain bola', 4),
  ('t4-013', 'MULIA', 'Berkeluhuran budi', 'Memiliki martabat tinggi', '5 huruf, sifat yang terpuji', 4),
  ('t4-014', 'NAFKAH', 'Pencarian untuk keluarga', 'Penghidupan dan rezeki', '6 huruf, dinafkahkah untuk orang tua', 4),
  ('t4-015', 'PADAHAL', 'Padahal tadinya', 'Kata sambung kontras', '7 huruf, menunjukkan kenyataan berbeda', 4),
  ('t4-016', 'RAHASIA', 'Sesuatu yang disembunyikan', 'Informasi yang tidak diketahui orang lain', '7 huruf, tidak boleh bocor', 4),
  ('t4-017', 'SABAR', 'Tahan menghadapi cobaan', 'Tabah dan tidak mengeluh', '5 huruf, kunci keberhasilan', 4),
  ('t4-018', 'TEPAT', 'Pas dan akurat', 'Sesuai sasaran', '5 huruf, tidak meleset sedikitpun', 4),
  ('t4-019', 'UTAMA', 'Paling penting', 'Yang terutama dan pertama', '5 huruf, prioritas utama', 4),
  ('t4-020', 'WIRASWASTA', 'Orang yang berusaha sendiri', 'Pengusaha mandiri', '10 huruf, pelaku bisnis', 4),
  ('t4-021', 'YAKIN', 'Percaya dengan sungguh', 'Keyakinan tanpa keraguan', '5 huruf, mantap dalam hati', 4),
  ('t4-022', 'BIMBANG', 'Ragu-ragu', 'Tidak tetap hati, bingung', '7 huruf, hati yang goyah', 4),
  ('t4-023', 'CELEBES', 'Nama lama pulau Sulawesi', 'Pulau di Indonesia timur', '7 huruf, berbentuk seperti huruf K', 4),
  ('t4-024', 'DOA', 'Permohonan kepada Tuhan', 'Harapan yang dipanjatkan', '3 huruf, meminta pertolongan', 4),
  ('t4-025', 'EMPATI', 'Merasa apa yang dirasakan orang lain', 'Kemampuan memahami perasaan orang', '6 huruf, tenggang rasa', 4),
  ('t4-026', 'GIGIH', 'Pantang menyerah', 'Tekun dan ulet dalam berusaha', '5 huruf, tak kenal lelah', 4),
  ('t4-027', 'HEBAT', 'Luar biasa', 'Sangat baik dan mengagumkan', '5 huruf, pretasi yang memukau', 4),
  ('t4-028', 'INTAN', 'Batu permata berkilau', 'Berlian yang sangat berharga', '5 huruf, carbon yang mengkristal', 4),
  ('t4-029', 'JATUH', 'Turun ke bawah', 'Gagal berdiri karena kehilangan keseimbangan', '5 huruf, jatuh itu wajar', 4),
  ('t4-030', 'KARYA', 'Hasil ciptaan', 'Produk dari kerja keras', '5 huruf, buah pemikiran atau keterampilan', 4),
  ('t5-001', 'ABADI', 'Kekal selama-lamanya', 'Tidak pernah berakhir', '5 huruf, langgeng sepanjang masa', 5),
  ('t5-002', 'BAKTI', 'Pengabdian setulus hati', 'Perbuatan yang menunjukkan kesetiaan', '5 huruf, kepada orang tua dan nusa bangsa', 5),
  ('t5-003', 'CEMERLANG', 'Bersinar terang', 'Gemilang dan mengagumkan', '9 huruf, prestasi yang bersinar', 5),
  ('t5-004', 'DIKSI', 'Pilihan kata', 'Pemilihan kata yang tepat', '5 huruf, seni memilih kata', 5),
  ('t5-005', 'ELEGAN', 'Anggun dan bermartabat', 'Berkelakuan halus dan sopan', '6 huruf, gaya yang mempesona', 5),
  ('t5-006', 'FENOMENA', 'Peristiwa luar biasa', 'Gejala yang dapat diamati', '8 huruf, kejadian yang langka', 5),
  ('t5-007', 'GAGASAN', 'Ide atau pikiran', 'Konsep dalam pemikiran', '7 huruf, buah dari imajinasi', 5),
  ('t5-008', 'HIKMAT', 'Kearifan dan kebijaksanaan', 'Pemahaman yang mendalam', '6 huruf, ilmu yang bermanfaat', 5),
  ('t5-009', 'INSPIRASI', 'Sumber ilham', 'Dorongan kreatif yang tiba-tiba', '9 huruf, percikan ide cemerlang', 5),
  ('t5-010', 'JERNIH', 'Bening dan bersih', 'Tidak keruh, jernih airnya', '6 huruf, bening tiada noda', 5),
  ('t5-011', 'KOMUNITAS', 'Kelompok orang', 'Masyarakat dalam lingkungan tertentu', '9 huruf, sekumpulan orang', 5),
  ('t5-012', 'LESTARI', 'Kekal dan abadi', 'Terjaga selamanya', '7 huruf, alam yang abadi', 5),
  ('t5-013', 'MISI', 'Tujuan yang hendak dicapai', 'Tugas khusus yang diemban', '4 huruf, visi dan misi', 5),
  ('t5-014', 'NOBAT', 'Mahkota kerajaan', 'Singgasana penguasa', '5 huruf, tempat duduk raja', 5),
  ('t5-015', 'OMBAK', 'Gelombang di laut', 'Gerakan air bergulung', '5 huruf, deburan di tepi pantai', 5),
  ('t5-016', 'PESONA', 'Daya tarik yang kuat', 'Keindahan yang memukau', '6 huruf, magnet hati', 5),
  ('t5-017', 'RESONANSI', 'Getaran yang berlanjut', 'Gaung yang terdengar kembali', '9 huruf, bunyi yang bergetar', 5),
  ('t5-018', 'SEJATI', 'Asli dan murni', 'Bukan tiruan', '6 huruf, hakiki dan sesungguhnya', 5),
  ('t5-019', 'TABIR', 'Tirai atau sekat', 'Penutup yang membatasi', '5 huruf, tabir misteri', 5),
  ('t5-020', 'ULTIMATUM', 'Peringatan terakhir', 'Tuntutan final yang tidak bisa ditawar', '9 huruf, ancaman terakhir', 5),
  ('t5-021', 'VITAL', 'Sangat penting', 'Esensial bagi kelangsungan', '5 huruf, peranan yang menentukan', 5),
  ('t5-022', 'WARISAN', 'Harta yang diturunkan', 'Peninggalan generasi ke generasi', '7 huruf, pusaka berharga', 5),
  ('t5-023', 'AKHLAK', 'Budi pekerti', 'Tingkah laku dan moral', '6 huruf, cermin kepribadian', 5),
  ('t5-024', 'BIJAK', 'Pandai dan berakal', 'Arif dalam bertindak', '5 huruf, sikap penuh pertimbangan', 5),
  ('t5-025', 'CENDEKIA', 'Cerdas dan berilmu', 'Terpelajar dan intelek', '8 huruf, kaum terdidik', 5),
  ('t5-026', 'DEDIKASI', 'Pengabdian penuh', 'Komitmen terhadap tugas', '8 huruf, totalitas dalam kerja', 5),
  ('t5-027', 'EKSOTIS', 'Keunikan yang memikat', 'Pesona khas yang berbeda', '7 huruf, keindahan yang jarang', 5),
  ('t5-028', 'KREASI', 'Hasil ciptaan baru', 'Inovasi yang orisinal', '6 huruf, daya cipta', 5),
  ('t5-029', 'MAESTRO', 'Ahli dalam bidang seni', 'Seniman besar yang diakui', '7 huruf, empu yang legendaris', 5),
  ('t5-030', 'NIRWANA', 'Keabadian yang damai', 'Kebahagiaan surgawi', '7 huruf, kesempurnaan jiwa', 5),
  ('t6-001', 'ALEGORI', 'Cerita kiasan', 'Karangan yang mengandung ibarat', '7 huruf, metafora yang diperluas', 6),
  ('t6-002', 'BENIGNA', 'Jinak dan tidak ganas', 'Bersifat baik dan ramah', '7 huruf, lawan dari maligna', 6),
  ('t6-003', 'DELIMA', 'Buah merah berbiji banyak', 'Buah yang melambangkan kesuburan', '6 huruf, buah surga', 6),
  ('t6-004', 'ELUSIF', 'Sulit ditangkap', 'Misterius dan sukar dipahami', '6 huruf, kabur dan menghindar', 6),
  ('t6-005', 'GENTING', 'Saat yang kritis', 'Keadaan yang menegangkan', '7 huruf, momen penuh ketegangan', 6),
  ('t6-006', 'HIJRAH', 'Perpindahan ke yang lebih baik', 'Meninggalkan kebiasaan buruk', '6 huruf, perubahan positif', 6),
  ('t6-007', 'INTEGRAL', 'Bagian yang tak terpisahkan', 'Komponen penting dalam keseluruhan', '8 huruf, esensial dan melekat', 6),
  ('t6-008', 'KACAMATA', 'Alat bantu penglihatan', 'Lensa untuk mata', '8 huruf, membantu melihat jelas', 6),
  ('t6-009', 'LIKUID', 'Benda cair', 'Zat yang mudah mengalir', '6 huruf, keadaan cair', 6),
  ('t6-010', 'MISTERI', 'Sesuatu yang belum terpecahkan', 'Teka-teki yang membingungkan', '7 huruf, enigma kehidupan', 6),
  ('t6-011', 'NARASI', 'Rangkaian cerita', 'Pengisahan suatu peristiwa', '6 huruf, alur dalam literatur', 6),
  ('t6-012', 'OKTAN', 'Kadar dalam bahan bakar', 'Ukuran kualitas bensin', '5 huruf, nilai dalam kendaraan', 6),
  ('t6-013', 'PIONIR', 'Pelopor dan perintis', 'Orang yang memulai pertama kali', '6 huruf, pembuka jalan', 6),
  ('t6-014', 'REFORMASI', 'Perubahan sistem', 'Transformasi menuju perbaikan', '9 huruf, perubahan besar', 6),
  ('t6-015', 'SINYAL', 'Isyarat atau tanda', 'Sinyal komunikasi', '6 huruf, pentunjuk yang dikirim', 6),
  ('t6-016', 'TRADISI', 'Kebiasaan turun-temurun', 'Warisan budaya yang diwariskan', '7 huruf, adat istiadat', 6),
  ('t6-017', 'VISI', 'Pandangan ke depan', 'Tujuan jangka panjang', '4 huruf, misi dan visi', 6),
  ('t6-018', 'WAWASAN', 'Pengetahuan yang luas', 'Pandangan dan pemahaman', '7 huruf, kebangsaan Indonesia', 6),
  ('t6-019', 'ANALISIS', 'Pemeriksaan mendalam', 'Penguraian masalah secara sistematis', '8 huruf, investigasi data', 6),
  ('t6-020', 'BLOOM', 'Proses mekar bahasa Inggris', 'Fase berbunga dalam Bahasa Inggris', '5 huruf, tahapan pembungaan', 6),
  ('t7-001', 'ARSITEK', 'Perancang bangunan', 'Profesi mendesain konstruksi', '7 huruf, insinyur bangunan', 7),
  ('t7-002', 'BIBLIOFIL', 'Pencinta buku', 'Kolektor buku langka', '9 huruf, hobi mengoleksi buku', 7),
  ('t7-003', 'CAGARBUDAYA', 'Warisan budaya yang dilindungi', 'Situs sejarah yang dijaga negara', '11 huruf, peninggalan berharga', 7),
  ('t7-004', 'DAHSYAT', 'Mengerikan tapi mengagumkan', 'Membuat takjub bercampur ngeri', '7 huruf, dahsyatnya alam', 7),
  ('t7-005', 'EKOSISTEM', 'Sistem kehidupan alam', 'Hubungan timbal balik makhluk hidup', '9 huruf, rantai kehidupan', 7),
  ('t7-006', 'FASILITAS', 'Sarana penunjang', 'Peralatan untuk memudahkan', '9 huruf, infrastruktur pendukung', 7),
  ('t7-007', 'GENERASI', 'Angkatan atau keturunan', 'Kumpulan individu yang lahir di era sama', '8 huruf, penerus bangsa', 7),
  ('t7-008', 'HARMONIS', 'Serasi dan selaras', 'Keselarasan dalam keragaman', '8 huruf, hidup berdampingan', 7),
  ('t7-009', 'ILMUWAN', 'Orang yang ahli ilmu', 'Seseorang yang mendalami sains', '7 huruf, intelektual peneliti', 7),
  ('t7-010', 'KEMERDEKAAN', 'Hari bersejarah Indonesia', 'Keadaan bebas dari penjajahan', '11 huruf, 17 Agustus 1945', 7),
  ('t7-011', 'LITERASI', 'Kemampuan baca tulis', 'Melek aksara dan pengetahuan', '8 huruf, budaya membaca', 7),
  ('t7-012', 'MEDITASI', 'Latihan konsentrasi', 'Menenangkan pikiran dengan duduk diam', '8 huruf, yoga pikiran', 7),
  ('t7-013', 'OPINI', 'Pendapat seseorang', 'Pandangan pribadi terhadap sesuatu', '5 huruf, opini publik', 7),
  ('t7-014', 'PROPORSIONAL', 'Seimbang dan sesuai', 'Berbanding lurus secara tepat', '12 huruf, adil dan merata', 7),
  ('t7-015', 'RAHMAT', 'Karunia dari yang kuasa', 'Anugerah dan nikmat', '6 huruf, berkah kehidupan', 7),
  ('t7-016', 'SIMPATIK', 'Menarik hati dan ramah', 'Mudah disukai orang lain', '8 huruf, pribadi menawan', 7),
  ('t7-017', 'TOLERANSI', 'Sikap menghargai perbedaan', 'Saling menghormati antar umat', '9 huruf, kerukunan beragama', 7),
  ('t7-018', 'UNIVERSAL', 'Berlaku di mana saja', 'Menyeluruh dan mendunia', '9 huruf, nilai-nilai global', 7),
  ('t7-019', 'VERIFIKASI', 'Pemeriksaan kebenaran', 'Proses validasi data', '10 huruf, konfirmasi identitas', 7),
  ('t7-020', 'WISDOM', 'Kebijaksanaan bahasa Inggris', 'Kearifan dalam bertindak', '6 huruf, wisdom teeth', 7),
  ('t8-001', 'ADILUHUNG', 'Bernilai seni tinggi', 'Agung dan sangat berharga', '9 huruf, budi pekerti yang luhur', 8),
  ('t8-002', 'BERIBADAH', 'Melakukan kewajiban spiritual', 'Berbakti kepada Tuhan', '9 huruf, menjalankan agama', 8),
  ('t8-003', 'BERSUKUR', 'Mengucap terima kasih', 'Bersyukur atas nikmat', '8 huruf, syukur kepada Tuhan', 8),
  ('t8-004', 'DEKADENSI', 'Kemerosotan moral', 'Masa penurunan peradaban', '9 huruf, degradasi nilai', 8),
  ('t8-005', 'FALSAFAH', 'Ajaran filsafat', 'Pandangan hidup yang mendalam', '8 huruf, filosofi kehidupan', 8),
  ('t8-006', 'FILANTROPI', 'Kedermawanan sosial', 'Kecintaan terhadap sesama', '10 huruf, donatur kemanusiaan', 8),
  ('t8-007', 'KEBERKAHAN', 'Karunia melimpah', 'Berkah yang berlipat', '10 huruf, anugerah kehidupan', 8),
  ('t8-008', 'KONSISTENSI', 'Tetap dan tidak berubah', 'Kestabilan dalam bertindak', '11 huruf, teguh pada pendirian', 8),
  ('t8-009', 'KONTEMPLASI', 'Perenungan mendalam', 'Meditasi penuh pemikiran', '11 huruf, meresapi kehidupan', 8),
  ('t8-010', 'KREATIVITAS', 'Daya cipta dan inovasi', 'Kemampuan mencipta hal baru', '11 huruf, imajinasi produktif', 8),
  ('t8-011', 'MAHAPENGERTI', 'Sangat memahami', 'Mengerti dengan sepenuh hati', '12 huruf, penuh pengertian', 8),
  ('t8-012', 'MUJIZAT', 'Peristiwa luar biasa', 'Keajaiban dari kuasa ilahi', '7 huruf, mukjizat Tuhan', 8),
  ('t8-013', 'MUSYAWARAH', 'Diskusi untuk mufakat', 'Perundingan mencapai kesepakatan', '10 huruf, tradisi Indonesia', 8),
  ('t8-014', 'PERADABAN', 'Tingkat kemajuan budaya', 'Kebudayaan yang maju', '9 huruf, civilisasi manusia', 8),
  ('t8-015', 'RESILIENSI', 'Ketahanan menghadapi cobaan', 'Kemampuan bangkit dari kegagalan', '10 huruf, mental baja', 8),
  ('t8-016', 'SILATURAHMI', 'Tali persaudaraan', 'Mempererat hubungan kekeluargaan', '11 huruf, menjalin persahabatan', 8),
  ('t8-017', 'SOLIDARITAS', 'Rasa setia kawan', 'Persatuan dan dukungan bersama', '11 huruf, kebersamaan', 8),
  ('t8-018', 'TRANSFORMASI', 'Perubahan bentuk', 'Metamorfosis total', '12 huruf, perubahan radikal', 8),
  ('t8-019', 'YURISPRUDENSI', 'Ilmu tentang hukum', 'Keputusan hukum yang menjadi rujukan', '13 huruf, undang-undang dasar', 8),
  ('t8-020', 'BERIMBANG', 'Sama berat dan setara', 'Seimbang dalam segala hal', '9 huruf, harmonis dan adil', 8),
  ('t9-001', 'BERSUJUD', 'Bersimpuh dalam doa', 'Menunduk dalam ibadah', '8 huruf, merendahkan diri', 9),
  ('t9-002', 'BIJAKSANA', 'Arif dan penuh pertimbangan', 'Memiliki kebijaksanaan hidup', '9 huruf, solomonic wisdom', 9),
  ('t9-003', 'BINTANGKEJORA', 'Rasi bintang yang terang', 'Gugusan bintang di langit malam', '13 huruf, gugusan bintang', 9),
  ('t9-004', 'CEMERLANG', 'Bersinar gemilang', 'Berkilau memancarkan cahaya', '9 huruf, pijar gemerlapan', 9),
  ('t9-005', 'KAKILANGIT', 'Ujung cakrawala', 'Garis pertemuan langit dan bumi', '10 huruf, horizon di kejauhan', 9),
  ('t9-006', 'KEMULIAAN', 'Keagungan yang hakiki', 'Kebesaran yang dihormati', '9 huruf, martabat tertinggi', 9),
  ('t9-007', 'KETENANGAN', 'Kedamaian batin', 'Hati yang tenteram dan damai', '10 huruf, zen dalam jiwa', 9),
  ('t9-008', 'MAHAGURU', 'Guru besar yang dihormati', 'Pendidik dengan ilmu mendalam', '8 huruf, profesor kehidupan', 9),
  ('t9-009', 'MEGAH', 'Mewah dan besar', 'Sangat elegan dan mencolok', '5 huruf, kemegahan istana', 9),
  ('t9-010', 'MENGUKIR', 'Membuat ukiran', 'Mencipta seni pada media keras', '8 huruf, mengukir kenangan', 9),
  ('t9-011', 'MERAJUT', 'Menyambung benang menjadi kain', 'Keterampilan tangan membuat pola', '7 huruf, merajut asa', 9),
  ('t9-012', 'PENCARAH', 'Pemberi nasihat yang bijak', 'Memberi arah pada yang bingung', '8 huruf, petunjuk jalan terang', 9),
  ('t9-013', 'PENGHARAPAN', 'Keyakinan akan masa depan', 'Optimisme yang menghidupkan', '11 huruf, harapan selalu ada', 9),
  ('t9-014', 'PERENUNGAN', 'Aktivitas kontemplasi', 'Merenung dalam keheningan', '10 huruf, duduk diam meresapi', 9),
  ('t9-015', 'PERJUANGAN', 'Usaha keras meraih tujuan', 'Perjuangan penuh pengorbanan', '10 huruf, fight for freedom', 9),
  ('t9-016', 'PITUTUR', 'Nasihat dari orang tua', 'Pesan bijak yang diwariskan', '7 huruf, petuah kehidupan', 9),
  ('t9-017', 'RENUNGAN', 'Buah dari meditasi', 'Pemikiran yang mendalam', '8 huruf, perenungan jiwa', 9),
  ('t9-018', 'SANUBARI', 'Hati yang paling dalam', 'Relung hati terdalam', '8 huruf, dari lubuk sanubari', 9),
  ('t9-019', 'SUSASTRA', 'Karya sastra tinggi', 'Tulisan bernilai seni-literasi', '8 huruf, seni keindahan bahasa', 9),
  ('t9-020', 'WAHYU', 'Petunjuk dari langit', 'Firman Tuhan kepada nabi', '5 huruf, ilham dari Yang Kuasa', 9),
  ('t10-001', 'ABADI', 'Kekal selamanya', 'Tak lekang oleh waktu', '5 huruf, abadi dalam sejarah', 10),
  ('t10-002', 'AKSARA', 'Sistem tulisan', 'Simbol yang melambangkan bunyi', '6 huruf, huruf yang sakral', 10),
  ('t10-003', 'AKULTURASI', 'Percampuran budaya', 'Pembauran dua kebudayaan berbeda', '10 huruf, peleburan tradisi', 10),
  ('t10-004', 'ESTETIKA', 'Ilmu tentang keindahan', 'Filsafat seni dan keelokan', '8 huruf, apresiasi keindahan', 10),
  ('t10-005', 'KARYASENI', 'Hasil karya kreatif', 'Produk dari ekspresi artistik', '9 huruf, masterpiece', 10),
  ('t10-006', 'KEABADIAN', 'Sifat kekal abadi', 'Keadaan tanpa awal dan akhir', '9 huruf, eternal life', 10),
  ('t10-007', 'KEFANAAN', 'Sifat sementara dunia', 'Ketidakabadian alam fana', '8 huruf, kehidupan yang sementara', 10),
  ('t10-008', 'MAKNAWI', 'Bersifat makna/rohani', 'Batiniah dan spiritual', '7 huruf, lebih dari sekedar lahir', 10),
  ('t10-009', 'MANUSIAWI', 'Bersifat kemanusiaan', 'Sesuai dengan sifat manusia', '9 huruf, penuh perikemanusiaan', 10),
  ('t10-010', 'MEMORABILIA', 'Benda-benda kenangan', 'Koleksi bernilai historis', '11 huruf, barang nostalgia', 10),
  ('t10-011', 'METAFORA', 'Kiasan dalam bahasa', 'Gaya bahasa perbandingan implisit', '8 huruf, majas perbandingan', 10),
  ('t10-012', 'MONUMENTAL', 'Berskala besar dan mengesankan', 'Karya yang sangat berarti', '10 huruf, pencapaian bersejarah', 10),
  ('t10-013', 'NIRLEKA', 'Buta aksara', 'Tidak bisa membaca dan menulis', '7 huruf, buta huruf', 10),
  ('t10-014', 'PUSAKA', 'Warisan berharga', 'Benda keramat peninggalan leluhur', '6 huruf, heirlooms keluarga', 10),
  ('t10-015', 'RELEVANSI', 'Keterkaitan yang bermakna', 'Sesuatu yang berhubungan dan berarti', '9 huruf, hubungan yang kontekstual', 10),
  ('t10-016', 'SELOKA', 'Puisi rakyat', 'Sajak yang mengandung petuah', '6 huruf, peribahasa dalam pantun', 10),
  ('t10-017', 'SPIRITUAL', 'Bersifat kejiwaan', 'Hal-hal yang berhubungan dengan roh', '9 huruf, dimensi batin', 10),
  ('t10-018', 'SUBLIMASI', 'Proses pengalihan ke lebih tinggi', 'Peningkatan ke taraf spiritual', '9 huruf, penyubliman jiwa', 10),
  ('t10-019', 'TRANSENDEN', 'Melampaui batas manusia', 'Di luar pengalaman fisik', '10 huruf, melampaui nalar', 10),
  ('t10-020', 'KEINDAHAN', 'Sifat yang elok', 'Kualitas yang menyenangkan mata', '9 huruf, estetika hakiki', 10)
on conflict (word_id) do nothing;

create index if not exists idx_vocabulary_tier on public.vocabulary (tier_level);
