// ============================================================
// KotaKata AI — Kurasi sisa placeholder TIER 8 (bagian B, 78–153).
// Key = kata, value = [c2, c3] bila c1 dipertahankan, atau
// [c1, c2, c3] bila c1 ikut diperbaiki (truncated/broken).
// ============================================================

export const REMAINING_T8B = {
  "heterotrof": ["makhluk hidup yang tidak dapat membuat makanannya sendiri", "Antonim: autotrof"],
  "hidraulika": ["ilmu tentang aliran dan tekanan zat cair", "istilah teknik tentang tenaga air"],
  "hidrofobia": ["gejala penyakit rabies berupa takut air", "istilah medis tentang fobia air"],
  "hiperkelas": ["golongan kata yang mencakup beberapa kelas berbeda", "istilah linguistik tentang kelompok kata"],
  "hipofremia": ["keterbelakangan mental atau kelemahan daya pikir", "istilah medis tentang lemah mental"],
  "hipsometer": ["alat pengukur tekanan udara dari titik didih air", "istilah meteorologi tentang alat ukur tinggi"],
  "hirsutisme": ["tumbuhnya rambut lebat di tempat yang tidak biasa pada wanita", "istilah medis tentang rambut berlebih"],
  "humanistis": ["menjunjung tinggi nilai dan martabat manusia", "Sinonim: perikemanusiaan"],
  "iatrogenik": ["penyakit yang timbul akibat tindakan atau kelalaian dokter", "istilah medis tentang penyakit akibat pengobatan"],
  "idealistis": ["berpegang teguh pada cita-cita dan kesempurnaan", "Sinonim: utopis"],
  "ikonometer": ["alat bantu untuk menaksir dimensi suatu benda", "istilah teknik tentang pengukur perkiraan"],
  "imunologis": ["berhubungan dengan sistem kekebalan tubuh", "istilah medis tentang daya tahan tubuh"],
  "imprimatur": ["izin resmi gereja untuk menerbitkan suatu karya", "istilah keagamaan tentang izin terbit"],
  "introjeksi": ["penerimaan sikap orang lain ke dalam diri secara tak sadar", "istilah psikologi tentang internalisasi"],
  "jongjorang": ["alat musik tradisional khas masyarakat Sunda", "istilah budaya Sunda tentang kesenian"],
  "kalamisani": ["jenis keris lurus dengan bilah lebar", "istilah budaya Jawa tentang senjata pusaka"],
  "kalistenik": ["senam kebugaran dengan gerakan tubuh tanpa alat", "istilah olahraga tentang latihan ringan"],
  "kardiogram": ["grafik yang mencatat denyut jantung", "istilah medis tentang rekaman jantung"],
  "kardiologi": ["cabang kedokteran yang menangani penyakit jantung", "istilah medis tentang kajian jantung"],
  "katekismus": ["buku tanya jawab pelajaran agama Kristen", "istilah agama tentang buku ajaran"],
  "kelengkiak": ["jenis semut berukuran besar dan kuat gigitannya", "istilah hewan tentang semut besar"],
  "kleidotomi": ["pemotongan tulang selangka untuk memudahkan kelahiran", "istilah medis tentang pertolongan persalinan"],
  "koagregasi": ["penggabungan tetes kabut menjadi tetes lebih besar", "istilah meteorologi tentang penyatuan awan"],
  "kolonoskop": ["alat pemeriksaan bagian dalam usus besar", "istilah medis tentang alat endoskopi"],
  "komunistis": ["berpaham kepemilikan bersama dan tanpa kelas", "istilah politik tentang paham kiri"],
  "konjungtur": ["pasang surut keadaan ekonomi dalam jangka pendek", "istilah ekonomi tentang siklus usaha"],
  "konsekrasi": ["pemberkatan roti dan anggur menjadi tubuh Kristus dalam misa", "istilah agama tentang pentahbisan"],
  "konsiliasi": ["upaya mendamaikan pihak yang berselisih", "Sinonim: perdamaian"],
  "konsistori": ["rapat para pejabat gereja untuk membicarakan urusan penting", "istilah keagamaan tentang badan gereja"],
  "konsonansi": ["pengulangan bunyi konsonan pada kata yang berdekatan", "istilah sastra tentang sajak konsonan"],
  "kranapaksa": ["masa dua pekan terakhir dalam kalender", "istilah penanggalan tentang paruh bulan"],
  "kriminolog": ["ahli yang mempelajari kejahatan dan sebabnya", "istilah ilmu hukum tentang pakar kriminal"],
  "kromotropi": ["sifat zat berubah warna karena pengaruh tertentu", "istilah kimia tentang perubahan warna"],
  "kronometer": ["jam presisi tinggi untuk navigasi", "Sinonim: jam pengukur"],
  "kuadruplet": ["empat bayi yang lahir dari satu kehamilan", "istilah medis tentang kelahiran ganda"],
  "kwasiorkor": ["penyakit kurang gizi berat pada anak-anak", "istilah medis tentang malnutrisi protein"],
  "laringitis": ["peradangan pada pangkal tenggorokan", "istilah medis tentang radang pita suara"],
  "leukopenia": ["berkurangnya sel darah putih dalam tubuh", "istilah medis tentang kekurangan leukosit"],
  "makromelia": ["kelainan berupa anggota tubuh yang tumbuh membesar", "istilah medis tentang anggota badan besar"],
  "malakofili": ["penyerbukan bunga yang dibantu siput atau keong", "istilah botani tentang perantara siput"],
  "matriarkat": ["sistem kekeluargaan yang dipimpin ibu", "Antonim: patriarkat"],
  "megamerger": ["penggabungan perusahaan-perusahaan raksasa", "istilah bisnis tentang merger besar"],
  "melankolia": ["kondisi depresi yang mendalam dan berkepanjangan", "Sinonim: kesedihan"],
  "metanefros": ["ginjal permanen pada hewan vertebrata tingkat tinggi", "istilah anatomi tentang ginjal akhir"],
  "metronimik": ["berdasarkan garis keturunan dari pihak ibu", "istilah antropologi tentang nama ibu"],
  "metronomis": ["berirama tetap seperti gerak metronom", "istilah musik tentang tempo tetap"],
  "miksoedema": ["penyakit akibat kekurangan hormon kelenjar gondok", "istilah medis tentang gangguan tiroid"],
  "morbiditas": ["angka perbandingan penderita penyakit di masyarakat", "istilah kesehatan tentang angka sakit"],
  "morfofonem": ["satuan bunyi yang muncul dari gabungan morfem", "istilah linguistik tentang bunyi morfem"],
  "multietnik": ["terdiri atas banyak kelompok suku bangsa", "Sinonim: majemuk"],
  "multifaset": ["mempunyai banyak aspek atau sisi", "Sinonim: beragam"],
  "multimeter": ["alat ukur listrik dengan berbagai fungsi pengukuran", "Sinonim: avometer"],
  "mumifikasi": ["proses pengawetan mayat hingga kering dan susut", "istilah sejarah tentang pengawetan jenazah"],
  "nasionisme": ["paham yang menekankan kepentingan bangsa sendiri", "Sinonim: nasionalisme"],
  "nematologi": ["cabang biologi yang mempelajari cacing", "istilah ilmiah tentang kajian cacing"],
  "neologisme": ["kata baru yang diciptakan untuk perkembangan bahasa", "istilah linguistik tentang kata bentukan baru"],
  "netralisme": ["sikap tidak memihak blok kekuatan mana pun", "istilah politik tentang ketidakberpihakan"],
  "nirgesekan": ["tanpa gesekan sehingga gerak hampir sempurna", "istilah fisika tentang tanpa hambatan"],
  "nonmiliter": ["tidak berkaitan dengan angkatan perang", "Antonim: militer"],
  "obituarium": ["berita duka tentang kematian seseorang di media", "Sinonim: berita duka"],
  "optometris": ["profesi kesehatan yang mengukur kelainan refraksi mata", "Sinonim: tukang kacamata"],
  "ovovivipar": ["cara berkembang biak dengan telur yang menetas di dalam tubuh induk", "istilah biologi tentang beranak bertelur"],
  "paleolitik": ["zaman batu tua pada masa prasejarah", "istilah sejarah tentang masa berburu"],
  "paraplegia": ["kelumpuhan pada kedua kaki dan bagian bawah tubuh", "istilah medis tentang lumpuh layuh"],
  "paratiroid": ["kelenjar kecil di leher yang mengatur kalsium darah", "istilah anatomi tentang kelenjar gondok kecil"],
  "pascalarva": ["tahap perkembangan hewan setelah masa larva", "istilah biologi tentang larva lanjut"],
  "pasimologi": ["cara berkomunikasi menggunakan gerakan tangan", "istilah linguistik tentang bahasa isyarat"],
  "patriarkat": ["sistem kekeluargaan yang dipimpin ayah", "Antonim: matriarkat"],
  "pentameter": ["bait puisi dengan lima tekanan ritmis", "istilah sastra tentang pola irama lima"],
  "peragawati": ["model wanita yang menampilkan pakaian di atas panggung", "Sinonim: model"],
  "periosteum": ["selaput pembungkus tulang yang kaya pembuluh darah", "istilah anatomi tentang selaput tulang"],
  "peristerit": ["batu permata berwarna biru berkilau dari golongan albit", "istilah mineralogi tentang batu bulan"],
  "perturbasi": ["penyimpangan orbit benda langit akibat gaya tarik lain", "istilah astronomi tentang gangguan orbit"],
  "perubalsem": ["salep berbau harum untuk pengobatan kulit", "istilah medis tentang obat luar"],
  "petarangan": ["sarang tempat ayam betina bertelur", "istilah peternakan tentang kandang bertelur"],
  "pigmentasi": ["pembentukan zat warna pada jaringan tubuh", "istilah biologi tentang warna kulit"],
  "planologis": ["berkaitan dengan ilmu perencanaan tata ruang", "istilah tata kota tentang perencanaan wilayah"],
  "platonisme": ["ajaran filsafat yang mengutamakan dunia ide", "istilah filsafat tentang aliran Plato"],
};
