// ============================================================
// KotaKata AI — Kurasi sisa placeholder TIER 8 (bagian A, 1–77).
// Key = kata, value = [c2, c3] bila c1 dipertahankan, atau
// [c1, c2, c3] bila c1 ikut diperbaiki (truncated/broken).
// ============================================================

export const REMAINING_T8A = {
  "ikonografi": ["studi tentang simbol dan gambar pada karya seni", "istilah seni rupa tentang perlambangan"],
  "kronologis": ["tersusun menurut urutan waktu kejadian", "Sinonim: berurutan"],
  "abstinensi": ["menahan diri dari kenikmatan atau kebiasaan tertentu", "istilah medis tentang pantangan"],
  "adiaktinik": ["tidak dapat ditembus sinar ultraviolet", "istilah kimia tentang tahan cahaya"],
  "akromegali": ["kelainan tubuh berupa pembesaran anggota badan", "istilah medis tentang gangguan pertumbuhan"],
  "aksidental": ["tanda kromatik yang mengubah tinggi nada dalam musik", "istilah musik tentang tanda tak terduga"],
  "aksiomatis": ["berlaku sebagai kebenaran yang tak perlu dibuktikan", "Sinonim: pasti"],
  "akumulator": ["alat penyimpan muatan listrik yang dapat diisi ulang", "Sinonim: aki"],
  "alomerisme": ["gejala kesamaan bentuk kristal pada zat yang berbeda", "istilah kimia tentang kristal serupa"],
  "amatirisme": ["kegiatan yang digeluti sebagai kesenangan, bukan pencarian nafkah", "Antonim: profesionalisme"],
  "anaptiksis": ["penambahan vokal di antara dua konsonan dalam ucapan", "istilah linguistik tentang vokal sisip"],
  "anggrekwan": ["orang yang membudidayakan tanaman anggrek", "Sinonim: pekebun anggrek"],
  "anisokoria": ["kelainan mata dengan ukuran pupil yang berbeda", "istilah medis tentang pupil tak sama"],
  "antarruang": ["berkaitan dengan hubungan antara satu ruang dan ruang lain", "Antonim: intraruang"],
  "antianemia": ["obat untuk mengatasi kekurangan sel darah merah", "istilah medis tentang pencegah kurang darah"],
  "antraknosa": ["penyakit tanaman yang menimbulkan bercak cokelat", "istilah pertanian tentang penyakit daun"],
  "apresorium": ["struktur jamur untuk melekat pada inang", "istilah biologi tentang alat hisap jamur"],
  "asidimeter": ["alat untuk mengukur kadar keasaman larutan", "Sinonim: pengukur asam"],
  "auskultasi": ["pemeriksaan dengan mendengarkan bunyi organ tubuh", "istilah medis tentang pemeriksaan stetoskop"],
  "balneologi": ["studi tentang pengobatan dengan air mineral", "istilah kesehatan tentang terapi air"],
  "barkometer": ["alat untuk mengukur kepekatan larutan penyamak kulit", "istilah industri kulit tentang pengukur"],
  "belongkang": ["perahu kecil bercadik yang biasa dipakai nelayan", "istilah pelayaran tentang perahu rata"],
  "belongkeng": ["keong kecil yang terdapat di sungai atau danau", "istilah perikanan tentang kerang kecil"],
  "biometrika": ["penerapan metode statistik pada data biologi", "istilah statistik tentang data hayati"],
  "biostatika": ["ilmu mengenai hubungan struktur dan fungsi makhluk hidup", "cabang biologi tentang keseimbangan bentuk tubuh", "istilah biologi tentang keseimbangan hayati"],
  "blastostil": ["cabang polip pada hewan berkoloni seperti ubur-ubur", "istilah zoologi tentang polip khusus"],
  "bradikardi": ["denyut jantung yang melambat di bawah normal", "Antonim: takikardia"],
  "densometer": ["alat pengukur kerapatan atau porositas kertas", "istilah percetakan tentang alat uji kertas"],
  "demisioner": ["kabinet yang telah mengembalikan mandat kepada kepala negara", "istilah ketatanegaraan tentang pemerintahan sementara"],
  "dermatitis": ["peradangan kulit yang menimbulkan rasa gatal", "Sinonim: eksim"],
  "dewanagari": ["aksara India yang menjadi dasar banyak huruf daerah", "istilah linguistik tentang tulisan India"],
  "diagenesis": ["proses perubahan endapan menjadi batuan sedimen", "istilah geologi tentang pembentukan sedimen"],
  "dielektrik": ["bahan penyekat yang tidak menghantarkan listrik", "Sinonim: isolator"],
  "dikromatik": ["mampu membedakan dua warna dasar cahaya", "istilah optik tentang penglihatan dua warna"],
  "diskontinu": ["terputus-putus dan tidak berkesinambungan", "Antonim: kontinu"],
  "diskordans": ["ketidakselarasan lapisan batuan yang berurutan", "istilah geologi tentang ketidakselarasan"],
  "diskorobik": ["senam irama dengan gerakan menari disko", "istilah olahraga tentang senam disko"],
  "disoperasi": ["kerja sama antarspesies yang merugikan salah satu pihak", "istilah biologi tentang interaksi merugikan"],
  "distingtif": ["berfungsi membedakan makna dalam ujaran", "istilah linguistik tentang ciri pembeda"],
  "duplisitas": ["jawaban kedua atas gugatan dalam proses peradilan", "istilah hukum tentang jawaban tergugat"],
  "egosentris": ["menilai segala hal dari sudut pandang diri sendiri", "Sinonim: mementingkan diri"],
  "ekospesies": ["kelompok organisme yang mampu saling kawin dalam satu lingkungan", "istilah ekologi tentang jenis setempat"],
  "eksfoliasi": ["pengelupasan kulit atau lapisan permukaan", "istilah kedokteran tentang pengelupasan kulit"],
  "ekuivokasi": ["pemakaian kata yang sama dengan makna berbeda", "istilah linguistik tentang makna ganda"],
  "emplasemen": ["tanah lapang yang disediakan untuk keperluan jawatan", "istilah perkeretaapian tentang area stasiun"],
  "enartrosis": ["sendi berbentuk bola yang bergerak ke segala arah", "istilah anatomi tentang sendi peluru"],
  "endodermis": ["lapisan sel terdalam pada akar tumbuhan", "istilah botani tentang lapisan dalam"],
  "endomiksis": ["proses penggantian inti sel tanpa perkawinan sel", "istilah biologi tentang pembaruan inti"],
  "endosmosis": ["masuknya cairan ke dalam sel melalui selaput", "Antonim: eksosmosis"],
  "endosperma": ["jaringan penyimpan cadangan makanan pada biji", "istilah botani tentang cadangan biji"],
  "endotoksin": ["racun yang dilepaskan bakteri saat selnya pecah", "istilah medis tentang racun kuman"],
  "enteropati": ["gangguan pada usus atau saluran pencernaan", "istilah medis tentang penyakit usus"],
  "entomologi": ["cabang biologi yang mempelajari serangga", "istilah ilmiah tentang kajian serangga"],
  "episiotomi": ["sayatan pada jalan lahir untuk mempermudah persalinan", "istilah medis tentang pertolongan persalinan"],
  "ergosterol": ["bahan dasar pembentukan vitamin D pada tumbuhan", "istilah kimia tentang provitamin D"],
  "ergoterapi": ["pengobatan dengan kegiatan kerja tertentu", "istilah medis tentang terapi aktivitas"],
  "erisipelas": ["infeksi kulit menular yang menimbulkan kemerahan", "istilah medis tentang radang kulit akut"],
  "etnobotani": ["kajian pemanfaatan tumbuhan oleh masyarakat tradisional", "istilah biologi tentang tumbuhan budaya"],
  "fekunditas": ["kemampuan menghasilkan keturunan atau telur", "istilah biologi tentang daya reproduksi"],
  "fibrinogen": ["protein darah yang berperan dalam pembekuan", "istilah medis tentang zat pembeku darah"],
  "fluktuatif": ["berubah-ubah naik turun secara tidak tetap", "Sinonim: labil"],
  "fotogravur": ["teknik cetak dengan bantuan cahaya pada logam", "istilah percetakan tentang ukir foto"],
  "gendarmeri": ["anggota kepolisian yang bertugas dalam militer", "istilah ketentaraan tentang polisi tentara"],
  "geranggang": ["senjata tradisional dari bambu yang diruncingkan", "Sinonim: tombak"],
  "gigantisme": ["kelainan berupa tubuh tumbuh terlalu besar", "istilah medis tentang pertumbuhan raksasa"],
  "ginekologi": ["cabang medis yang menangani penyakit kewanitaan", "istilah medis tentang kesehatan reproduksi wanita"],
  "glikosuria": ["adanya gula dalam urine karena kadar gula darah tinggi", "istilah medis tentang gula dalam air seni"],
  "glomerulus": ["gulungan pembuluh darah pada ginjal tempat penyaringan", "istilah anatomi tentang penyaring ginjal"],
  "granolitik": ["bahan lantai dari campuran hancuran batu dan semen", "istilah bangunan tentang lantai batu"],
  "heliometer": ["teleskop untuk mengukur diameter matahari", "istilah astronomi tentang alat ukur matahari"],
  "hemeralopi": ["gangguan penglihatan saat cahaya terang", "istilah medis tentang buta siang"],
  "hemostatik": ["obat yang menghentikan pendarahan dengan mempercepat pembekuan", "istilah medis tentang penghenti darah"],
  "henoteisme": ["pemujaan satu tuhan tanpa menolak keberadaan dewa lain", "istilah agama tentang pemujaan tunggal"],
  "heterofemi": ["kesalahan memakai kata dalam berbahasa", "istilah linguistik tentang salah kata"],
  "heteronomi": ["ketergantungan pada hukum atau kekuasaan dari luar", "Antonim: otonomi"],
};
