// ============================================================
// KotaKata AI — Kurasi sisa placeholder TIER 9 (85 kata).
// Key = kata, value = [c2, c3] bila c1 dipertahankan, atau
// [c1, c2, c3] bila c1 ikut diperbaiki (truncated/broken).
// ============================================================

export const REMAINING_T9 = {
  "telemetri": ["teknik pengukuran data dari jarak jauh lalu mengirimkannya ke alat penerima", "istilah teknologi tentang pengukuran nirkabel"],
  "pamungkas": ["bagian penutup dari suatu rangkaian", "Sinonim: final"],
  "lokakarya": ["pertemuan para ahli untuk membahas masalah praktis di bidangnya", "Sinonim: sanggar kerja"],
  "destroyer": ["kapal perang yang cepat dan lincah untuk mengawal armada", "Sinonim: kapal perusak"],
  "tarantula": ["laba-laba besar berbulu yang hidup di daerah tropis", "Sinonim: laba-laba besar"],
  "translasi": ["pergeseran semua titik pada bidang dengan jarak dan arah yang sama", "istilah matematika tentang perpindahan bentuk"],
  "kompulsif": ["dorongan kuat yang tak tertahankan untuk berbuat sesuatu", "istilah psikologi tentang perilaku terpaksa"],
  "terngiang": ["suara yang terus terdengar dalam ingatan", "Contoh: namanya masih … di telingaku"],
  "altimeter": ["alat pengukur ketinggian tempat dari permukaan bumi berdasarkan tekanan udara", "instrumen yang biasa dipakai di pesawat terbang"],
  "neurologi": ["cabang kedokteran yang mempelajari sistem saraf", "Sinonim: ilmu saraf"],
  "vasektomi": ["operasi pemotongan saluran sperma untuk memandulkan pria", "istilah medis tentang kontrasepsi pria"],
  "kloroform": ["cairan mudah menguap berbau eter yang dipakai sebagai pelarut atau pembius", "Sinonim: triklorometana"],
  "stetoskop": ["alat dokter untuk mendengarkan bunyi kerja alat tubuh dalam rongga dada", "Sinonim: alat dengar medis"],
  "pengurang": ["bilangan yang dikurangkan dari bilangan lain dalam operasi hitung", "Antonim: penambah"],
  "abaktinal": ["sisi tubuh hewan yang berlawanan dengan sisi bermulut", "istilah zoologi tentang bagian punggung"],
  "adaptabel": ["mudah menyesuaikan diri dengan lingkungan atau kondisi baru", "Sinonim: fleksibel"],
  "adibusana": ["busana rancangan khusus yang bermutu tinggi", "istilah mode tentang pakaian kelas atas"],
  "adjektiva": ["kata yang menerangkan nomina; kata sifat", "memberi keterangan tentang sifat atau keadaan suatu benda", "Sinonim: ajektif"],
  "aglutinin": ["zat dalam darah yang menggumpalkan bakteri atau sel darah merah", "istilah imunologi tentang penggumpal antigen"],
  "agregatif": ["berkaitan dengan penggabungan menjadi satu kesatuan", "istilah ekonomi tentang permintaan menyeluruh"],
  "agriologi": ["pengkajian sejarah dan adat istiadat suku bangsa", "ilmu tentang kebudayaan masyarakat sederhana", "istilah antropologi tentang kajian budaya"],
  "agrokimia": ["bahan kimia yang digunakan dalam bidang pertanian", "istilah pertanian tentang pupuk dan pestisida"],
  "almamater": ["perguruan tinggi tempat seseorang menuntut ilmu", "Sinonim: kampus asal"],
  "ametropia": ["kehilangan kemampuan memfokuskan bayangan pada retina karena ketidaksesuaian ukuran bola mata", "kelainan mata seperti rabun jauh atau rabun dekat", "istilah medis tentang gangguan refraksi"],
  "androgini": ["keadaan memiliki ciri laki-laki dan perempuan sekaligus", "istilah biologi tentang dua kelamin dalam satu tubuh"],
  "anemograf": ["alat untuk merekam arah dan kecepatan angin", "instrumen meteorologi pencatat angin otomatis", "istilah meteorologi tentang alat cuaca"],
  "anemogram": ["catatan atau grafik tentang arah dan kecepatan angin", "hasil rekaman alat pengukur angin", "istilah meteorologi tentang data angin"],
  "aneuploid": ["keadaan jumlah kromosom yang tidak kelipatan tepat dari jumlah dasar", "istilah genetika tentang kelainan kromosom"],
  "antarsuku": ["menghubungkan kelompok etnis yang berlainan", "Antonim: intrasuku"],
  "antinovel": ["karya sastra yang menolak kaidah novel konvensional", "istilah sastra tentang eksperimen bentuk naratif"],
  "araknitis": ["peradangan pada selaput tipis pembungkus otak", "istilah medis tentang radang selaput otak"],
  "argometer": ["alat taksi yang menghitung biaya berdasarkan jarak tempuh", "Sinonim: taksimeter"],
  "arteriola": ["pembuluh darah kecil antara arteri dan kapiler", "istilah anatomi tentang cabang arteri"],
  "asimetris": ["bentuk yang tidak setangkup bila dibelah dua", "Antonim: simetris"],
  "asistensi": ["kegiatan membantu seseorang dalam tugas profesionalnya", "istilah akademik tentang pendamping dosen"],
  "audiogram": ["grafik ketajaman pendengaran terhadap berbagai nada", "istilah medis tentang hasil tes telinga"],
  "azospermi": ["ketiadaan sperma hidup dalam air mani sehingga mandul", "istilah medis tentang kemandulan pria"],
  "baitulmal": ["lembaga keuangan negara dalam sistem Islam yang mengelola harta umat", "Sinonim: kas negara"],
  "barometri": ["ilmu pengukuran tekanan udara atmosfer", "istilah meteorologi tentang tekanan udara"],
  "bebekisme": ["sikap mengikuti pendapat orang lain secara membabi buta", "Sinonim: peniruan"],
  "benzedrin": ["zat perangsang yang menambah kewaspadaan", "istilah medis tentang amfetamin"],
  "bioritmik": ["irama alami tubuh yang memengaruhi kondisi fisik dan mental", "istilah biologi tentang siklus hayati"],
  "brakiurus": ["hewan berkaki pendek atau berbadan pendek", "istilah zoologi tentang bentuk tubuh pendek"],
  "ciriwangi": ["tanda pengikat pernikahan adat Sunda bernilai sepuluh kali tanda pertunangan", "istilah budaya Sunda tentang seserahan"],
  "deflorasi": ["robeknya selaput pada organ intim wanita", "istilah medis tentang keperawanan"],
  "defoliasi": ["kerontokan daun pada pohon", "istilah botani tentang gugurnya daun"],
  "dekantasi": ["pemisahan endapan dari cairan dengan menuangkan cairan bening", "istilah kimia tentang pengendapan"],
  "delinkuen": ["orang yang berperilaku melanggar aturan atau hukum", "Sinonim: nakal"],
  "deuterium": ["isotop hidrogen dengan berat jenis dua kali hidrogen biasa", "Sinonim: hidrogen berat"],
  "diklorida": ["senyawa yang molekulnya mengandung dua atom klorin", "istilah kimia tentang klorida ganda"],
  "difluensi": ["pola garis angin atau isobar yang memancar menjauh", "istilah meteorologi tentang penyebaran angin"],
  "digenesis": ["perkembangbiakan melalui dua cara, seksual dan aseksual", "istilah biologi tentang reproduksi ganda"],
  "diminutif": ["bentuk kata yang menyatakan makna kecil atau sayang", "istilah linguistik tentang kata kecil"],
  "dinamisme": ["kepercayaan bahwa benda alam memiliki kekuatan gaib", "istilah antropologi tentang kekuatan sakti"],
  "diskiasis": ["kelainan tumbuhnya dua baris bulu mata", "istilah medis tentang bulu mata ganda"],
  "disosiasi": ["penguraian molekul menjadi molekul yang lebih sederhana", "istilah kimia tentang perpecahan senyawa"],
  "dodekagon": ["bangun datar bersisi dua belas", "istilah geometri tentang poligon duabelas"],
  "ekatantri": ["alat musik petik India berdawai tunggal", "istilah musik tentang alat petik tradisional"],
  "ekliptika": ["lintasan yang tampak dilalui matahari jika dilihat dari bumi", "istilah astronomi tentang bidang orbit bumi"],
  "ekshalasi": ["pengembusan udara dari paru-paru; mengeluarkan napas", "Antonim: inhalasi"],
  "elokuensi": ["kemampuan berbicara dengan lancar dan meyakinkan", "Sinonim: kefasihan"],
  "endosemen": ["pengalihan hak milik dengan tanda tangan di balik dokumen", "istilah perbankan tentang pengesahan cek"],
  "energetik": ["penuh semangat dan tenaga", "Sinonim: bertenaga"],
  "enteritis": ["peradangan pada usus", "istilah medis tentang radang usus"],
  "entogenus": ["organisme yang tumbuh di dalam tubuh organisme lain", "makhluk hidup yang berkembang di dalam inang", "istilah biologi tentang parasit internal"],
  "epibentos": ["organisme yang hidup menempel di permukaan dasar laut atau danau", "istilah biologi laut tentang penghuni dasar"],
  "epifiotik": ["wabah penyakit tumbuhan yang menyebar cepat dan mengganas", "istilah pertanian tentang epidemi tanaman"],
  "episkopal": ["berkaitan dengan pemerintahan gereja oleh uskup", "istilah agama tentang sistem keuskupan"],
  "etimologi": ["cabang ilmu bahasa tentang asal-usul kata dan perubahannya", "Sinonim: ilmu asal kata"],
  "etnografi": ["studi deskriptif tentang kebudayaan suku-suku bangsa", "istilah antropologi tentang gambaran budaya"],
  "evaluatif": ["berkaitan dengan penilaian atau taksiran", "Sinonim: penilaian"],
  "eviserasi": ["pengeluaran organ dalam dari rongga tubuh", "istilah medis tentang pembedahan dalam"],
  "fitokimia": ["ilmu tentang senyawa kimia yang terkandung dalam tumbuhan", "istilah biologi tentang zat tanaman"],
  "fitostrot": ["makhluk yang penyebarannya dibantu oleh tumbuhan", "istilah ekologi tentang perantara tanaman"],
  "flegmatis": ["bertemperamen tenang dan tidak mudah terpancing emosi", "istilah psikologi tentang sifat kalem"],
  "fotometri": ["pengukuran intensitas atau kekuatan cahaya", "istilah fisika tentang ukuran cahaya"],
  "freatofit": ["tanaman yang akarnya menjangkau air tanah", "istilah botani tentang tumbuhan air tanah"],
  "gametosit": ["sel induk yang menghasilkan sel kelamin", "istilah biologi tentang sel pembentuk gamet"],
  "gelembong": ["celana yang lebar pada bagian kangkang", "istilah mode tentang celana longgar"],
  "genderuwo": ["makhluk halus berwujud manusia bertubuh besar", "istilah kepercayaan rakyat tentang hantu"],
  "gerenjeng": ["lembaran logam tipis untuk membungkus makanan", "Sinonim: aluminium foil"],
  "geriatrik": ["ilmu kedokteran tentang perawatan kesehatan orang lanjut usia", "cabang medis yang menangani penyakit usia tua", "istilah medis tentang perawatan lansia"],
  "gerinding": ["alat musik yang dibunyikan dengan menempelkannya pada mulut", "istilah musik tradisional tentang bunyi berdengung"],
  "hedonisme": ["pandangan yang menganggap kesenangan sebagai tujuan utama hidup", "gaya hidup yang mengejar kenikmatan semata", "Antonim: asketisme"],
  "hektograf": ["alat kuno untuk memperbanyak tulisan tangan", "istilah perkantoran tentang pengganda dokumen"],
};
