// ============================================================
// KotaKata AI — Kurasi sisa placeholder TIER 10 (63 kata).
// Key = kata, value = [c2, c3] bila c1 dipertahankan, atau
// [c1, c2, c3] bila c1 ikut diperbaiki (truncated/broken).
// Semua kolom: tanpa "Merupakan kata X", tanpa bocor jawaban,
// tanpa duplikat/substring >=12 huruf antar kolom.
// ============================================================

export const REMAINING_T10 = {
  "kolektif": ["dilakukan atau dimiliki secara bersama-sama oleh banyak orang", "Antonim: individual"],
  "diameter": ["garis yang menghubungkan dua titik pada lingkaran melalui titik pusatnya", "tali busur terpanjang dalam lingkaran"],
  "prosesor": ["komponen utama komputer yang menjalankan instruksi program", "Sinonim: pengolah data"],
  "apoteker": ["ahli yang meracik dan menyerahkan obat berdasarkan resep dokter", "Sinonim: farmasis"],
  "sanitasi": ["usaha untuk membina dan menciptakan suatu keadaan yang baik di bidang kesehatan, terutama kesehatan masyarakat", "cara menyehatkan lingkungan hidup manusia terutama lingkungan fisik, yaitu tanah, air, dan udara", "Sinonim: higiene"],
  "genosida": ["tindakan pemusnahan massal secara sistematis terhadap suatu kelompok bangsa", "Sinonim: pembantaian"],
  "imajiner": ["bersifat khayalan atau tidak nyata", "Antonim: nyata"],
  "obesitas": ["penumpukan lemak yang berlebihan di dalam badan; kegemukan yang berlebih", "keadaan berat badan jauh di atas normal", "Antonim: kurus"],
  "psikosis": ["kelainan jiwa yang disertai dengan disintegrasi kepribadian dan gangguan kontak dengan kenyataan", "gangguan mental berat yang membuat penderitanya kehilangan akal sehat", "istilah medis tentang gangguan jiwa parah"],
  "berjamur": ["mulai ditumbuhi jamur karena lembap", "Contoh: roti itu sudah … karena disimpan terlalu lama"],
  "dengusan": ["bunyi binatang seperti lembu, kerbau, kuda saat mengembuskan napas", "embusan napas keras melalui hidung pada hewan", "Sinonim: dengus"],
  "pesangon": ["uang yang diberikan kepada karyawan saat berhenti bekerja", "Sinonim: uang pisah"],
  "pranikah": ["masa persiapan sebelum melangsungkan pernikahan", "Antonim: pascanikah"],
  "nautilus": ["binatang laut yang kecil; siput laut bercangkang indah", "moluska laut yang cangkangnya terbagi dalam ruang-ruang", "penghuni laut purba yang masih hidup"],
  "tertanda": ["sudah dibubuhi tanda tangan", "sudah ditandatangani oleh pihak berwenang", "Sinonim: ditandatangani"],
  "bergelar": ["menyandang gelar akademik atau kehormatan", "Contoh: ia … sarjana ekonomi dari universitas ternama"],
  "mengerik": ["mengeluarkan bunyi rik yang berulang-ulang", "Sinonim: berkerik"],
  "taklukan": ["orang (daerah, negara, dan sebagainya) yang ditaklukkan", "wilayah yang berhasil dikuasai dalam peperangan", "Sinonim: jajahan"],
  "periskop": ["alat pengintai pada kapal selam untuk melihat keadaan di permukaan laut", "Sinonim: teropong"],
  "bersisik": ["tubuhnya tertutup lempengan keras seperti pada ikan", "Antonim: licin"],
  "partitur": ["tulisan notasi musik yang memuat seluruh bagian lagu", "Sinonim: skor"],
  "kelegaan": ["perihal (keadaan) lega; rasa lega", "perasaan senang karena beban atau kekhawatiran hilang", "Antonim: kecemasan"],
  "perancah": ["bangunan sementara dari bambu atau papan sebagai tumpuan pekerja", "istilah konstruksi tentang penyangga kerja"],
  "neurotik": ["berada dalam keadaan sakit saraf atau gangguan jiwa ringan", "istilah psikologi tentang gangguan kecemasan", "Antonim: waras"],
  "klarinet": ["alat musik tiup dari kayu dengan lidah tunggal yang bergetar", "tergolong alat musik tiup kayu bernada tinggi"],
  "harmonik": ["nada tambahan yang menyertai nada dasar dengan frekuensi berlipat-lipat", "istilah musik tentang deret nada di atas nada dasar"],
  "opsional": ["boleh dipilih atau tidak dipilih sesuai kebutuhan", "Antonim: wajib"],
  "kefanaan": ["keadaan tidak kekal di dunia", "Antonim: keabadian"],
  "pabrikan": ["orang yang bertanggung jawab atas pembuatan barang di pabrik; pengusaha pabrik", "pihak yang memproduksi barang secara massal", "Sinonim: produsen"],
  "kolumnis": ["penulis tetap rubrik opini di media massa", "Sinonim: penulis"],
  "poligami": ["perkawinan seorang pria dengan lebih dari satu istri dalam waktu bersamaan", "Antonim: monogami"],
  "stigmata": ["tanda luka pada tubuh yang menyerupai luka penyaliban", "istilah keagamaan tentang luka mukjizat"],
  "oligarki": ["pemerintahan oleh sekelompok kecil orang yang berkuasa", "Antonim: demokrasi"],
  "absorben": ["bahan yang mampu menyerap cairan atau gas", "Sinonim: penyerap"],
  "adenosis": ["kelainan berupa pembesaran atau pertumbuhan berlebih pada kelenjar", "istilah medis tentang gangguan kelenjar tubuh"],
  "adinamia": ["keadaan lemah tanpa tenaga", "istilah medis tentang keletihan berlebih", "Antonim: bertenaga"],
  "adiratna": ["batu permata yang sangat berharga", "Sinonim: mustika"],
  "adiwarna": ["sangat elok dan memukau", "Sinonim: permai"],
  "adsorpsi": ["peristiwa menempelnya partikel pada permukaan suatu benda", "istilah kimia tentang daya serap permukaan"],
  "agradasi": ["pengendapan yang meninggikan permukaan tanah", "istilah geologi tentang peninggian dasar sungai"],
  "agroikos": ["pemain yang menjadi bulan-bulanan atau bahan tertawaan dalam sandiwara", "istilah teater tentang pelawak pemeran figuran"],
  "aksostil": ["batang tipis penyokong pada tubuh organisme bersel satu", "istilah biologi tentang struktur penunjang sel"],
  "aktinida": ["deret unsur kimia radioaktif bernomor atom 89 hingga 103", "istilah kimia tentang unsur transuranium"],
  "akusatif": ["bentuk kasus yang menandai fungsi objek dalam kalimat", "istilah linguistik tentang kasus objek"],
  "almandit": ["varietas garnet berwarna merah tua", "batu mulia merah yang biasa dijadikan akik", "Sinonim: garnet"],
  "alotropi": ["kemampuan suatu unsur wujud dalam beberapa bentuk berbeda", "istilah kimia tentang bentuk lain suatu unsur"],
  "anatomis": ["berkaitan dengan susunan tubuh makhluk hidup", "Sinonim: struktural"],
  "aniridia": ["kelainan bawaan pada mata yang tidak memiliki selaput pelangi", "istilah medis tentang ketiadaan iris"],
  "anteliks": ["tonjolan memanjang pada daun telinga", "bagian telinga yang terlipat ke dalam", "istilah anatomi tentang lipatan telinga luar"],
  "antibeku": ["cairan yang ditambahkan untuk mencegah pembekuan mesin", "Sinonim: antifreeze"],
  "antologi": ["buku kumpulan karya pilihan dari satu atau beberapa pengarang", "Sinonim: bunga rampai"],
  "apatride": ["orang yang tidak memiliki kewarganegaraan", "Antonim: warga negara"],
  "araknoid": ["selaput tipis di antara selaput otak keras dan lunak", "istilah anatomi tentang selaput saraf pusat"],
  "artisyok": ["tanaman sayur yang kuncup bunganya dimakan", "istilah kuliner tentang sayuran khas Eropa"],
  "autogami": ["penyerbukan sendiri pada tumbuhan dengan serbuk sari bunganya sendiri", "istilah biologi tentang perkawinan sendiri"],
  "autogram": ["tulisan tangan sendiri sebagai tanda pengenal", "Sinonim: tanda tangan"],
  "autoklaf": ["alat sterilisasi berupa ruang kedap udara bertekanan tinggi", "istilah laboratorium tentang pensteril uap"],
  "azeotrop": ["campuran zat cair yang titik didihnya tetap", "istilah kimia tentang campuran tidak terpisahkan"],
  "barzanji": ["syair pujian yang berisi riwayat Nabi Muhammad saw.", "bacaan yang sering dibawakan saat perayaan Maulid"],
  "basilika": ["bangunan Romawi kuno berbentuk persegi panjang dengan deretan pilar", "istilah arsitektur tentang gereja bergaya kuno"],
  "bilineal": ["prinsip keturunan yang memperhitungkan garis kekerabatan dua pihak", "istilah antropologi tentang sistem keturunan ganda"],
  "biprisma": ["prisma ganda dengan sudut puncak sedikit kurang dari 180 derajat", "istilah fisika tentang alat pembias cahaya"],
  "birofaks": ["pesawat telekomunikasi untuk mengirim dokumen, data, dan gambar melalui faksimile", "alat pengirim salinan dokumen lewat saluran telepon", "Sinonim: mesin faks"],
};
